// Generated by tauri-specta from apps/desktop/src-tauri (`just bindings`). Don't edit.
// biome-ignore-all lint: generated
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Whether books are open, and if not, whether to set up or unlock. */
	sessionState: () => __TAURI_INVOKE<SessionStateDto>("session_state"),
	/**  Creates new books protected by `passphrase`; returns the recovery key to show once. */
	createEntity: (setup: EntitySetupDto, passphrase: string) => typedError<RecoveryKeyDto, IpcFailure>(__TAURI_INVOKE("create_entity", { setup, passphrase })),
	/**  Checks the user saved the recovery key, by its last group. */
	confirmRecoveryKey: (lastGroup: string) => typedError<boolean, IpcFailure>(__TAURI_INVOKE("confirm_recovery_key", { lastGroup })),
	/**  Unlocks with the passphrase; `remember` keeps the key in the OS keychain. */
	unlock: (passphrase: string, remember: boolean) => typedError<SessionStateDto, IpcFailure>(__TAURI_INVOKE("unlock", { passphrase, remember })),
	/**  Opens the books with the recovery key and a new passphrase; returns the new recovery key. */
	recover: (recoveryKey: string, newPassphrase: string) => typedError<RecoveryKeyDto, IpcFailure>(__TAURI_INVOKE("recover", { recoveryKey, newPassphrase })),
	/**  Opens the demo books instead. */
	openDemo: () => typedError<SessionStateDto, IpcFailure>(__TAURI_INVOKE("open_demo")),
	/**  The backups there are, and the policy. */
	backups: () => typedError<BackupsDto, IpcFailure>(__TAURI_INVOKE("backups")),
	/**  Backs up now. */
	backupNow: () => typedError<BackupDto, IpcFailure>(__TAURI_INVOKE("backup_now")),
	/**  Restores the newest backup into a scratch folder and checks it. */
	restoreDrill: () => typedError<DrillDto, IpcFailure>(__TAURI_INVOKE("restore_drill")),
	/**  Build information. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  The open entity. */
	entity: () => __TAURI_INVOKE<EntityDto>("entity"),
	/**  Accounting periods. */
	periods: () => typedError<PeriodDto[], IpcFailure>(__TAURI_INVOKE("periods")),
	/**  Profit and loss for a date range. */
	profitAndLoss: (from: string, to: string) => typedError<ProfitAndLossDto, IpcFailure>(__TAURI_INVOKE("profit_and_loss", { from, to })),
	/**  Balance sheet as of a date. */
	balanceSheet: (asOf: string) => typedError<BalanceSheetDto, IpcFailure>(__TAURI_INVOKE("balance_sheet", { asOf })),
	/**  Trial balance. */
	trialBalance: (from: string | null, to: string) => typedError<TrialBalanceDto, IpcFailure>(__TAURI_INVOKE("trial_balance", { from, to })),
	/**  Cash basis (*daňová evidence*) for a date range. */
	cashBasis: (from: string, to: string) => typedError<CashBasisDto, IpcFailure>(__TAURI_INVOKE("cash_basis", { from, to })),
	/**  Posted journal entries in a date range. */
	journal: (from: string, to: string) => typedError<JournalEntryDto[], IpcFailure>(__TAURI_INVOKE("journal", { from, to })),
	/**  Hash chain and balance, for the status line. */
	integrity: () => typedError<IntegrityDto, IpcFailure>(__TAURI_INVOKE("integrity")),
	/**  Invoices. */
	invoices: () => typedError<InvoiceDto[], IpcFailure>(__TAURI_INVOKE("invoices")),
	/**  The latest bank import with its tie-out. */
	bankStatement: () => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("bank_statement")),
	/**  The inbox. */
	proposals: () => typedError<ProposalDto[], IpcFailure>(__TAURI_INVOKE("proposals")),
	/**  The egress register. */
	egressRegister: () => typedError<EgressRunDto[], IpcFailure>(__TAURI_INVOKE("egress_register")),
	/**  Exactly what one run sent ("What was shared"). */
	egressPayload: (id: string) => typedError<EgressPayloadDto, IpcFailure>(__TAURI_INVOKE("egress_payload", { id })),
	/**  Each advisor task, what it may send, and the user's policy. */
	egressPolicies: () => __TAURI_INVOKE<EgressPolicyDto[]>("egress_policies"),
	/**  Sets a task's policy: `always`, `ask` or `never`. */
	setEgressPolicy: (task: string, policy: string) => typedError<EgressPolicyDto[], IpcFailure>(__TAURI_INVOKE("set_egress_policy", { task, policy })),
	/**  The DPH return for a period, mapped by the rule pack. */
	vatReturn: (from: string, to: string) => typedError<VatReturnDto, IpcFailure>(__TAURI_INVOKE("vat_return", { from, to })),
	/**  The kontrolní hlášení for a period, checked against the return. */
	controlStatement: (from: string, to: string) => typedError<ControlStatementDto, IpcFailure>(__TAURI_INVOKE("control_statement", { from, to })),
	/**  The § 7 scenarios, from the books or the user's projection. */
	incomeTaxScenarios: (projection: {
	/**  § 7 income, e.g. `1 571 000`. */
	income: string,
	/**  Actual tax-deductible expenses. */
	expenses: string,
	/**  `craft`, `trade` or `liberal`; empty when unknown. */
	flatRate: string | null,
	/**  A planned purchase, for the timing lever (may be empty). */
	purchaseDescription: string,
	/**  Its price excluding claimable VAT (empty for none). */
	purchasePrice: string,
} | null) => typedError<TaxScenariosDto, IpcFailure>(__TAURI_INVOKE("income_tax_scenarios", { projection })),
	/**
	 *  Asks the tax advisor to explain the scenarios; every figure is checked
	 *  against the engine. `confirmed` answers the "ask before each run" policy.
	 */
	runTaxAdvisor: (projection: {
	/**  § 7 income, e.g. `1 571 000`. */
	income: string,
	/**  Actual tax-deductible expenses. */
	expenses: string,
	/**  `craft`, `trade` or `liberal`; empty when unknown. */
	flatRate: string | null,
	/**  A planned purchase, for the timing lever (may be empty). */
	purchaseDescription: string,
	/**  Its price excluding claimable VAT (empty for none). */
	purchasePrice: string,
} | null, confirmed: boolean) => typedError<TaxAdviceDto, IpcFailure>(__TAURI_INVOKE("run_tax_advisor", { projection, confirmed })),
	/**  The financial advisor's findings for the last complete quarter. */
	financialFindings: () => typedError<FindingDto[], IpcFailure>(__TAURI_INVOKE("financial_findings")),
	/**  "Explain this" on an account or an entry, citing the entries behind it. */
	explain: (target: ExplainTargetDto, confirmed: boolean) => typedError<ExplanationDto, IpcFailure>(__TAURI_INVOKE("explain", { target, confirmed })),
	/**  The obligations calendar for a year, from the pack. */
	obligations: (year: number) => typedError<ObligationDto[], IpcFailure>(__TAURI_INVOKE("obligations", { year })),
	/**  Whether advisors can run, and what to do if not. */
	advisorStatus: () => __TAURI_INVOKE<AdvisorStatusDto>("advisor_status"),
	/**  The rule pack in force, with citations. */
	rulePack: () => __TAURI_INVOKE<RulePackDto>("rule_pack"),
	/**  A document rendered to PDF (`cs` or `en`), base64-encoded. */
	invoicePdf: (id: number, lang: string) => typedError<DocumentPdfDto, IpcFailure>(__TAURI_INVOKE("invoice_pdf", { id, lang })),
	/**  An issued document as XML: `isdoc`, `ubl` (Peppol BIS 3.0) or `cii`. */
	invoiceXml: (id: number, format: string) => typedError<DocumentXmlDto, IpcFailure>(__TAURI_INVOKE("invoice_xml", { id, format })),
	/**  Reminders due on a date, drafted for the user to send. */
	dunningQueue: (asOf: string) => typedError<DunningNoticeDto[], IpcFailure>(__TAURI_INVOKE("dunning_queue", { asOf })),
	/**  Recurring invoice templates and their next runs. */
	recurringTemplates: () => typedError<RecurringTemplateDto[], IpcFailure>(__TAURI_INVOKE("recurring_templates")),
	/**  What the invoice editor offers. */
	invoiceForm: () => typedError<InvoiceFormDto, IpcFailure>(__TAURI_INVOKE("invoice_form")),
	/**  Saves a draft typed in the editor; the core parses and checks it. */
	createInvoiceDraft: (draft: InvoiceDraftDto) => typedError<InvoiceDto, IpcFailure>(__TAURI_INVOKE("create_invoice_draft", { draft })),
	/**  Issues a draft: the next number, posted through the kernel. */
	issueInvoice: (id: number, issueDate: string) => typedError<InvoiceDto, IpcFailure>(__TAURI_INVOKE("issue_invoice", { id, issueDate })),
	/**  Deletes a draft. */
	deleteInvoiceDraft: (id: number) => typedError<null, IpcFailure>(__TAURI_INVOKE("delete_invoice_draft", { id })),
	/**  Imports a statement file (base64): tied out and deduplicated first. */
	importBankStatement: (fileName: string, contentBase64: string) => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("import_bank_statement", { fileName, contentBase64 })),
	/**  What importing invoices from Pohoda or Fakturoid would do; changes nothing. */
	previewInvoiceImport: (fileName: string, contentBase64: string) => typedError<ImportPreviewDto, IpcFailure>(__TAURI_INVOKE("preview_invoice_import", { fileName, contentBase64 })),
	/**  Posts the new invoices in a Pohoda or Fakturoid export. */
	commitInvoiceImport: (fileName: string, contentBase64: string) => typedError<ImportPreviewDto, IpcFailure>(__TAURI_INVOKE("commit_invoice_import", { fileName, contentBase64 })),
	/**
	 *  Everything in the books as one reproducible zip (base64). The zip isn't
	 *  encrypted, so real books ask for the passphrase again first.
	 */
	exportBooks: (passphrase: string | null) => typedError<ExportDto, IpcFailure>(__TAURI_INVOKE("export_books", { passphrase })),
	/**  Whether the opt-in update check is on, and what it last found. */
	updateStatus: () => __TAURI_INVOKE<UpdateStatusDto>("update_status"),
	/**  What the purchase editor offers. */
	purchaseForm: () => typedError<PurchaseFormDto, IpcFailure>(__TAURI_INVOKE("purchase_form")),
	/**  The periods the screens report on, as of the books' date. */
	reportingPeriods: () => typedError<ReportingPeriodsDto, IpcFailure>(__TAURI_INVOKE("reporting_periods")),
	/**  Every received invoice, with what's paid. */
	purchases: () => typedError<PurchaseDto[], IpcFailure>(__TAURI_INVOKE("purchases")),
	/**  Records a received invoice: checked, posted, the supplier kept. */
	recordPurchase: (draft: PurchaseDraftDto) => typedError<PurchaseDto, IpcFailure>(__TAURI_INVOKE("record_purchase", { draft })),
	/**  Turns the update check on or off. */
	setUpdateCheck: (enabled: boolean) => __TAURI_INVOKE<UpdateStatusDto>("set_update_check", { enabled }),
	/**  Checks the project's signed release manifest for a newer version. */
	checkForUpdate: () => typedError<UpdateStatusDto, IpcFailure>(__TAURI_INVOKE("check_for_update")),
	/**  Accepts every line the matcher or a rule is certain about. */
	acceptCertainBankLines: () => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("accept_certain_bank_lines")),
	/**  Books a line as the user chose: invoices, or account rows (a split). */
	bookBankLine: (line: string, allocations: BankAllocationDto[]) => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("book_bank_line", { line, allocations })),
	/**  Makes a rule from a line and books the line by it. */
	createBankRule: (line: string, rule: BankRuleInputDto) => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("create_bank_rule", { line, rule })),
	/**  Reference data loaded, where it came from, and whether fetching is on. */
	referenceData: () => typedError<RefDataDto, IpcFailure>(__TAURI_INVOKE("reference_data")),
	/**  Imports a ČNB rates file (`cnb_fx`) or a repo-rate history (`cnb_repo`). */
	importReferenceData: (kind: string, fileName: string, text: string) => typedError<RefDataDto, IpcFailure>(__TAURI_INVOKE("import_reference_data", { kind, fileName, text })),
	/**  Turns fetching from the ČNB on or off (off by default). */
	setReferenceFetch: (enabled: boolean) => typedError<RefDataDto, IpcFailure>(__TAURI_INVOKE("set_reference_fetch", { enabled })),
	/**  Fetches the ČNB's rates for a day, only when fetching is on. */
	fetchCnbRates: (date: string) => typedError<RefDataDto, IpcFailure>(__TAURI_INVOKE("fetch_cnb_rates", { date })),
	/**  Checks a signed rule-pack update. */
	installPackUpdate: (packToml: string, signature: string) => typedError<PackUpdateDto, IpcFailure>(__TAURI_INVOKE("install_pack_update", { packToml, signature })),
};

/* Types */
/**  An account the user can pick. */
export type AccountChoiceDto = {
	/**  Code. */
	code: string,
	/**  Name. */
	name: string,
};

/**  Whether advisors can run, and what to do if not. */
export type AdvisorStatusDto = {
	/**  `claude-code-cli` or `fake`. */
	provider: string,
	/**  `ready`, `not_installed`, `not_signed_in` or `rate_limited`. */
	state: string,
	/**  What the provider reports about itself, when ready. */
	version: string | null,
	/**  Where the CLI was looked for, when it wasn't found. */
	lookedIn: string[],
	/**  When a usage limit resets (UTC, RFC 3339), if known. */
	resetsAt: string | null,
	/**  Runs replay recordings; no model is called. */
	demo: boolean,
};

/**  Build information. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Core version. */
	version: string,
};

/**  One backup. */
export type BackupDto = {
	/**  The file. */
	file: string,
	/**  When (UTC). */
	createdAt: string,
	/**  Size. */
	bytes: number,
	/**  The journal's chain head it anchors. */
	chainHead: string | null,
};

/**  The backups and the policy. */
export type BackupsDto = {
	/**  The demo keeps its books in memory and has none. */
	demo: boolean,
	/**  Where they go. */
	folder: string | null,
	/**  Every this many days. */
	everyDays: number,
	/**  How many are kept. */
	keep: number,
	/**  Newest first. */
	backups: BackupDto[],
};

/**  Balance sheet. */
export type BalanceSheetDto = {
	/**  The date. */
	asOf: string,
	/**  Asset lines. */
	assets: StatementLineDto[],
	/**  Liability lines. */
	liabilities: StatementLineDto[],
	/**  Equity lines. */
	equity: StatementLineDto[],
	/**  Profit not yet closed into equity. */
	unclosedProfit: MoneyDto,
	/**  Sum of assets. */
	totalAssets: MoneyDto,
	/**  Sum of liabilities. */
	totalLiabilities: MoneyDto,
	/**  Equity including the unclosed profit. */
	totalEquity: MoneyDto,
	/**  Assets equal liabilities plus equity. */
	balances: boolean,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**
 *  One part of how a line is booked: an invoice to settle (by its ledger
 *  entry) or an account row with an optional VAT code. Amounts as typed.
 */
export type BankAllocationDto = {
	/**  The invoice's ledger entry. */
	entryId: number | null,
	/**  Or an account. */
	account: string | null,
	/**  Input VAT code for an account row. */
	vatCode: string | null,
	/**  Gross amount, e.g. `3 630,00`. */
	amount: string,
};

/**  One imported file. */
export type BankImportDto = {
	/**  File name. */
	file: string,
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  New lines it brought. */
	lines: number,
	/**  Its closing balance. */
	closing: MoneyDto | null,
};

/**  A bank statement line in the workbench. */
export type BankLineDto = {
	/**  Stable id: `s<import>-<line>`. */
	id: string,
	/**  Booking date. */
	date: string,
	/**  Who (or the bank's text when no party is named). */
	counterparty: string,
	/**  The other party's account, canonical. */
	counterpartyAccount: string | null,
	/**  Symbols and message. */
	reference: string,
	/**  Signed amount. */
	amount: MoneyDto,
	/**  `certain` (accepted with one press), `needs_you`, or `booked`. */
	status: string,
	/**  What it was booked as. */
	bookedAs: string | null,
	/**  The entry it was booked as. */
	entryId: number | null,
	/**  What the workbench proposes, e.g. `Settle 2026-102`. */
	proposal: string | null,
	/**  Why it isn't accepted with one press. */
	heldBecause: string | null,
	/**  An inbox proposal about the line. */
	proposalId: string | null,
	/**  Scored candidates. */
	candidates: MatchCandidateDto[],
};

/**  A bank rule. */
export type BankRuleDto = {
	/**  Id. */
	id: number,
	/**  Name. */
	name: string,
	/**  When and what, in words. */
	summary: string,
	/**  Accepted with the certain ones. */
	autoAccept: boolean,
};

/**  A rule as the user creates it from a line. */
export type BankRuleInputDto = {
	/**  Name. */
	name: string,
	/**  The account to book to. */
	account: string,
	/**  An input VAT code, when the payments carry VAT. */
	vatCode: string | null,
	/**  Accept future lines it fits with the certain ones. */
	autoAccept: boolean,
};

/**  The bank workbench. */
export type BankStatementDto = {
	/**  `221 · ČSOB Business ··4412`. */
	accountName: string,
	/**  The latest file. */
	file: string,
	/**  Its format. */
	format: string,
	/**  Its first day. */
	from: string,
	/**  Its last day. */
	to: string,
	/**  Its opening balance. */
	opening: MoneyDto,
	/**  Money in. */
	credits: MoneyDto,
	/**  Money out. */
	debits: MoneyDto,
	/**  Opening + lines. */
	closing: MoneyDto,
	/**  What the bank reports. */
	reportedClosing: MoneyDto,
	/**  Always true: a statement that doesn't tie out is refused at import. */
	tiesOut: boolean,
	/**  Every import, oldest first. */
	imports: BankImportDto[],
	/**  Every line, newest first. */
	lines: BankLineDto[],
	/**  The user's rules. */
	rules: BankRuleDto[],
	/**  Accounts a line can be booked to. */
	accounts: AccountChoiceDto[],
	/**  Input VAT codes a purchase can carry. */
	vatCodes: VatCodeChoiceDto[],
};

/**  Cash basis (*daňová evidence*). */
export type CashBasisDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Every recognition. */
	lines: CashBasisLineDto[],
	/**  Totals per direction and treatment. */
	totals: CashBasisTotalDto[],
	/**  Taxable income. */
	taxableIncome: MoneyDto,
	/**  Deductible expenses. */
	deductibleExpenses: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A cash-basis recognition. */
export type CashBasisLineDto = {
	/**  Payment date. */
	date: string,
	/**  The payment entry. */
	cashEntryId: number,
	/**  The settled entry, if any. */
	settledEntryId: number | null,
	/**  Revenue or expense account. */
	account: string,
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The recognised amount. */
	amount: MoneyDto,
};

/**  A cash-basis total. */
export type CashBasisTotalDto = {
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The total. */
	amount: MoneyDto,
};

/**  A customer. */
export type ClientDto = {
	/**  Legal name. */
	name: string,
	/**  IČO. */
	ico: string | null,
	/**  DIČ. */
	dic: string | null,
	/**  Postal address. */
	address: string | null,
};

/**  The kontrolní hlášení for a period. */
export type ControlStatementDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Documents above this (VAT included) are itemised. */
	threshold: MoneyDto,
	/**  Services received from the EU. */
	a2: KhItemDto[],
	/**  Supplies to VAT payers above the threshold. */
	a4: KhItemDto[],
	/**  Every other supply. */
	a5: KhTotalsDto,
	/**  Purchases from VAT payers above the threshold. */
	b2: KhItemDto[],
	/**  Every other purchase. */
	b3: KhTotalsDto,
	/**  Section C against the DPH return's rows. */
	c: KhCRowDto[],
	/**  Every section C row equals the return's. */
	matchesReturn: boolean,
	/**  Documents that couldn't be placed. */
	problems: string[],
	/**  The filing deadline from the pack. */
	dueOn: string,
	/**  Pack provenance. */
	pack: string,
};

/**  A rendered document, ready to save or open. */
export type DocumentPdfDto = {
	/**  Suggested file name, e.g. `Faktura 2026-041.pdf`. */
	fileName: string,
	/**  The PDF, base64-encoded. */
	pdfBase64: string,
	/**  Pages in the PDF. */
	pages: number,
	/**  The QR Platba payload, if the document asks for a payment. */
	spayd: string | null,
};

/**  A document written in an exchange format (ISDOC, UBL, CII). */
export type DocumentXmlDto = {
	/**  Suggested file name, e.g. `2026-041.isdoc`. */
	fileName: string,
	/**  The file's media type. */
	mediaType: string,
	/**  The XML. */
	xml: string,
};

/**  What the restore drill found. */
export type DrillDto = {
	/**  The backup checked. */
	file: string,
	/**  Everything checked out. */
	passed: boolean,
	/**  The file is the one its manifest describes. */
	fileMatches: boolean,
	/**  It opened with the key. */
	opens: boolean,
	/**  Its content matches the manifest. */
	contentMatches: boolean,
	/**  Its chain head matches the manifest. */
	chainMatches: boolean | null,
};

/**  A reminder that is due, drafted for the user to send. */
export type DunningNoticeDto = {
	/**  The invoice. */
	documentId: number,
	/**  Its number. */
	number: string,
	/**  Who owes. */
	customer: string,
	/**  The step, from 1. */
	step: number,
	/**  `friendly`, `firm` or `final`. */
	tone: string,
	/**  When the invoice was due. */
	dueOn: string,
	/**  When this step became due. */
	scheduledOn: string,
	/**  Days past due. */
	daysOverdue: number,
	/**  Still owed. */
	open: MoneyDto,
	/**  The late interest stated on the final step. */
	interest: LateInterestDto | null,
	/**  Why the interest is missing (no ČNB rate history imported). */
	interestProblem: string | null,
	/**  Draft subject, Czech. */
	subjectCs: string,
	/**  Draft body, Czech. */
	bodyCs: string,
	/**  Draft subject, English. */
	subjectEn: string,
	/**  Draft body, English. */
	bodyEn: string,
};

/**  Exactly what one run sent. */
export type EgressPayloadDto = {
	/**  The run. */
	id: string,
	/**  Bytes sent. */
	bytes: number,
	/**  The run's link in the register's chain. */
	hash: string,
	/**  The payload, pretty-printed when it's JSON. */
	text: string,
};

/**  A task type, what it may send, and the user's policy. */
export type EgressPolicyDto = {
	/**  Task id. */
	task: string,
	/**  Which advisor. */
	advisor: string,
	/**  For people. */
	label: string,
	/**  What it may send. */
	scope: string[],
	/**  `always`, `ask` or `never`. */
	policy: string,
};

/**  One run in the egress register. */
export type EgressRunDto = {
	/**  Stable id. */
	id: string,
	/**  RFC 3339 UTC. */
	at: string,
	/**  Which advisor. */
	advisor: string,
	/**  What for. */
	purpose: string,
	/**  The provider, e.g. the user's Claude Code installation. */
	provider: string,
	/**  The model setting used. */
	model: string,
	/**  What left the machine, summarised. */
	sent: string,
	/**  Fields removed by the egress gate. */
	redacted: string[],
	/**  MCP tool calls answered. */
	toolCalls: number,
	/**  Bytes sent, prompts and tool results together. */
	bytesSent: number,
	/**  What came of it. */
	outcome: string,
	/**  The provider's own cost estimate, when it gave one. */
	costNote: string | null,
	/**  The register's hash chain is unbroken up to and including this run. */
	intact: boolean,
};

/**  The open entity. */
export type EntityDto = {
	/**  Shown in the source list. */
	displayName: string,
	/**  `OSVČ` or `s.r.o.`. */
	legalForm: string,
	/**  `monthly`, `quarterly` or `non-payer`. */
	vatPeriod: string,
	/**  ISO 4217. */
	functionalCurrency: string,
	/**  The date the books are seen from (today, or the demo's fixed date). */
	asOf: string,
	/**  Bank account label, masked. */
	bankName: string,
};

/**  The first-run form: who the books are for. */
export type EntitySetupDto = {
	/**  The name on invoices (an OSVČ's own name, or a trade name). */
	displayName: string,
	/**  IČO (may be empty while registering). */
	ico: string,
	/**  DIČ, for VAT payers. */
	dic: string | null,
	/**  The address printed on invoices. */
	address: string,
	/**  `monthly`, `quarterly` or `none`. */
	vatPeriod: string,
	/**  The trade-register line printed on invoices. */
	registration: string,
	/**  The business account's IBAN. */
	iban: string | null,
	/**  The bank's name, for the status line. */
	bankName: string,
	/**  An email for invoices. */
	email: string | null,
	/**  `craft`, `trade` or `liberal`, when known. */
	flatRateGroup: string | null,
};

/**  What to explain: an account over a period, or one entry. */
export type ExplainTargetDto = {
	/**  `account` or `entry`. */
	kind: string,
	/**  For an account. */
	account: string | null,
	/**  First day, for an account. */
	from: string | null,
	/**  Last day, for an account. */
	to: string | null,
	/**  For an entry. */
	entry: number | null,
};

/**  An entry behind a figure. */
export type ExplainedEntryDto = {
	/**  Entry id. */
	id: number,
	/**  Date. */
	date: string,
	/**  Memo. */
	memo: string,
	/**  Its amount on the account (or its gross, for an entry). */
	amount: MoneyDto,
};

/**  An explanation, checked against the books. */
export type ExplanationDto = {
	/**  `accepted`, `rejected`, `needs_confirmation`, `blocked`, `failed`. */
	status: string,
	/**  The explanation, when accepted. */
	text: string | null,
	/**  Entries it cites, when accepted. */
	cites: number[],
	/**  Why it was rejected or didn't run. */
	problems: string[],
	/**  Figures matched to the books. */
	grounded: number,
	/**  The register entry. */
	runId: string | null,
	/**  Every entry behind the figure. */
	entries: ExplainedEntryDto[],
};

/**  The full export, as one zip. */
export type ExportDto = {
	/**  Suggested file name. */
	fileName: string,
	/**  Files inside. */
	files: number,
	/**  Its size. */
	bytes: number,
	/**  The zip, base64. */
	contentBase64: string,
};

/**  A detector's finding, citing the entries it rests on. */
export type FindingDto = {
	/**  Stable id. */
	id: string,
	/**  `variance`, `vendor_rate`, `client_margin`, `late_payer`, `subscription`, `runway`. */
	detector: string,
	/**  One line. */
	title: string,
	/**  Second line. */
	detail: string,
	/**  The period it's about. */
	period: string,
	/**  Its figures. */
	figures: ([string, MoneyDto])[],
	/**  Its percentages, whole percent. */
	percents: ([string, string])[],
	/**  Journal entries it rests on. */
	cites: number[],
};

/**  One document in an invoice import. */
export type ImportDocumentDto = {
	/**  Where in the file (item or row). */
	position: number,
	/**  Its number. */
	number: string,
	/**  `invoice` or `credit_note`. */
	kind: string,
	/**  Issued. */
	issueDate: string,
	/**  The customer's name. */
	customer: string,
	/**  Base. */
	base: MoneyDto,
	/**  VAT. */
	vat: MoneyDto,
	/**  Total. */
	total: MoneyDto,
	/**  `new`, `duplicate` or `problem`. */
	status: string,
	/**  Why it isn't new. */
	problems: string[],
};

/**  What an invoice import holds, or did. */
export type ImportPreviewDto = {
	/**  File name. */
	file: string,
	/**  `Pohoda` or `Fakturoid`. */
	source: string,
	/**  Documents that would be posted. */
	new: number,
	/**  Every document read. */
	documents: ImportDocumentDto[],
	/**  What in the file couldn't be read. */
	problems: string[],
	/**  After a commit: the numbers posted. */
	imported: string[],
};

/**  Journal integrity for the status line. */
export type IntegrityDto = {
	/**  Every posted entry fits the hash chain. */
	chainIntact: boolean,
	/**  Posted entries verified. */
	entriesChecked: number,
	/**  The verified chain head. */
	head: string | null,
	/**  The first break, described, if any. */
	firstBreak: string | null,
	/**  Debits equal credits across the journal. */
	balanced: boolean,
};

/**  A stretch of delay at a constant principal. */
export type InterestPeriodDto = {
	/**  First day. */
	from: string,
	/**  Last day, inclusive. */
	to: string,
	/**  Days. */
	days: number,
	/**  What was owed. */
	principal: MoneyDto,
	/**  Interest. */
	interest: MoneyDto,
};

/**  A draft invoice as typed in the editor. The core parses and checks it. */
export type InvoiceDraftDto = {
	/**
	 *  A customer's legal name, as [`InvoiceFormDto::clients`] lists them;
	 *  empty for a new customer.
	 */
	client: string,
	/**
	 *  A customer not on any document yet, when `client` is empty. Saving
	 *  the draft adds them to the list.
	 */
	newClient: ClientDto | null,
	/**  Days from today to the due date. */
	dueDays: number,
	/**  Free text printed on the invoice. */
	note: string,
	/**  The lines. */
	lines: InvoiceDraftLineDto[],
};

/**  A line as typed: Czech number formats (`1,5`, `1 200,00`). */
export type InvoiceDraftLineDto = {
	/**  What was supplied. */
	description: string,
	/**  Quantity, e.g. `21` or `1,5`. */
	quantity: string,
	/**  Unit, e.g. `h`. */
	unit: string,
	/**  Price per unit excluding VAT, e.g. `1 200,00`. */
	unitPrice: string,
	/**  One of [`InvoiceFormDto::vat_codes`]. */
	vatCode: string,
};

/**  An issued (or drafted) invoice. */
export type InvoiceDto = {
	/**  Document id. */
	id: number,
	/**  Invoice number, once issued. */
	number: string | null,
	/**  Client name. */
	client: string,
	/**  `draft`, `scheduled`, `open`, `overdue`, `partPaid`, `paid`, `credited`. */
	status: string,
	/**  Issue date (posted invoices). */
	issuedOn: string | null,
	/**  Due date. */
	dueOn: string | null,
	/**  When a scheduled invoice will be issued. */
	scheduledFor: string | null,
	/**  When it was paid in full. */
	paidOn: string | null,
	/**  Days past due, when overdue and open. */
	daysOverdue: number | null,
	/**  Excluding VAT. */
	base: MoneyDto,
	/**  VAT. */
	vat: MoneyDto,
	/**  Total. */
	gross: MoneyDto,
	/**  Paid so far. */
	paid: MoneyDto,
	/**  Credited by credit notes. */
	credited: MoneyDto,
	/**  Still open. */
	open: MoneyDto,
	/**  The lines. */
	lines: InvoiceLineDto[],
	/**  The posted journal entry, if issued. */
	entryId: number | null,
	/**  The rule pack its totals were fixed with, once issued. */
	pack: string | null,
};

/**  What the invoice editor offers. */
export type InvoiceFormDto = {
	/**  Customers seen on earlier documents. */
	clients: ClientDto[],
	/**  The VAT codes this supplier may put on a sale. */
	vatCodes: VatCodeChoiceDto[],
	/**  Units the line editor suggests. */
	units: string[],
	/**  Payment terms the editor offers, in days. */
	dueDays: number[],
	/**  Today: the issue date a draft issued now gets. */
	today: string,
	/**  The number the next invoice issued today gets. */
	nextNumber: string,
};

/**  One invoice line. */
export type InvoiceLineDto = {
	/**  What was supplied. */
	description: string,
	/**  Quantity as written, e.g. `56`. */
	quantity: string,
	/**  Unit, e.g. `h`. */
	unit: string,
	/**  Price per unit, excluding VAT. */
	unitPrice: MoneyDto,
	/**  The rule pack's VAT code. */
	vatCode: string,
	/**  Its rate in percent on the document date, from the rule pack. */
	vatRatePercent: string,
	/**  Quantity × unit price. */
	base: MoneyDto,
	/**  VAT on the line. */
	vat: MoneyDto,
};

/**
 *  The error every command returns to the webview: a stable code and a
 *  message for people.
 */
export type IpcFailure = {
	/**  `ledger`, `bad_request`, `demo`, `out_of_range`, `money`. */
	code: string,
	/**  What went wrong. */
	message: string,
};

/**  A posted journal entry. */
export type JournalEntryDto = {
	/**  Row id. */
	id: number,
	/**  Accounting date. */
	date: string,
	/**  Gapless posting number. */
	postedSeq: number | null,
	/**  `manual`, `invoice`, `bank`, `rule`, `advisor`, `reversal`, `opening`. */
	sourceKind: string,
	/**  Origin reference. */
	sourceRef: string | null,
	/**  Description. */
	memo: string,
	/**  Approver, when recorded. */
	approvedBy: string | null,
	/**  The entry it reverses. */
	reversesId: number | null,
	/**  The lines. */
	lines: JournalLineDto[],
};

/**  A journal line. */
export type JournalLineDto = {
	/**  One-based. */
	lineNo: number,
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Amount in the line's currency; debit positive. */
	amount: MoneyDto,
	/**  Functional-currency amount. */
	functional: MoneyDto,
	/**  FX rate for foreign lines. */
	fxRate: string | null,
	/**  VAT code. */
	vatCode: string | null,
	/**  Free text. */
	memo: string,
};

/**  One section C row. */
export type KhCRowDto = {
	/**  The return row. */
	row: string,
	/**  What the statement totals. */
	base: MoneyDto,
	/**  What the return says. */
	returnBase: MoneyDto,
	/**  They agree. */
	matches: boolean,
};

/**  An itemised line. */
export type KhItemDto = {
	/**  Document number. */
	number: string,
	/**  The other party. */
	counterparty: string,
	/**  Their VAT id. */
	vatId: string,
	/**  DUZP or DPPD. */
	date: string,
	/**  Base, standard rate. */
	baseStandard: MoneyDto,
	/**  Tax, standard rate. */
	taxStandard: MoneyDto,
	/**  Base, reduced rate. */
	baseReduced: MoneyDto,
	/**  Tax, reduced rate. */
	taxReduced: MoneyDto,
	/**  Base at both rates. */
	base: MoneyDto,
	/**  Tax at both rates. */
	tax: MoneyDto,
};

/**  A summary section. */
export type KhTotalsDto = {
	/**  Base, standard rate. */
	baseStandard: MoneyDto,
	/**  Tax, standard rate. */
	taxStandard: MoneyDto,
	/**  Base, reduced rate. */
	baseReduced: MoneyDto,
	/**  Tax, reduced rate. */
	taxReduced: MoneyDto,
	/**  Documents counted. */
	documents: number,
};

/**  Statutory late interest on one receivable. */
export type LateInterestDto = {
	/**  The first day of delay. */
	delayFrom: string,
	/**  The half-year start whose ČNB repo rate applies. */
	rateDate: string,
	/**  Annual percent, e.g. `11.5`. */
	annualRate: string,
	/**  One period per stretch at a constant principal. */
	periods: InterestPeriodDto[],
	/**  Sum of the periods. */
	total: MoneyDto,
	/**  The statutory minimum recovery cost. */
	recoveryCost: MoneyDto,
};

/**  A candidate document for a bank line. */
export type MatchCandidateDto = {
	/**  E.g. `Invoice 2026-102 · Studio Brno`. */
	label: string,
	/**  Key facts. */
	detail: string,
	/**  `0.96`. */
	score: string,
	/**  `certain`, `likely`, `needs_you`, `unlikely`. */
	confidence: string,
	/**  The score as a sum of named contributions. */
	contributions: ScoreContributionDto[],
};

/**  An amount in integer minor units (`8470000` CZK is 84 700,00 Kč). */
export type MoneyDto = {
	/**  Minor units; always within ±(2^53 − 1). */
	minor: number,
	/**  ISO 4217 code. */
	currency: string,
};

/**  One deadline in the obligations calendar. */
export type ObligationDto = {
	/**  The pack's obligation id. */
	obligation: string,
	/**  For people. */
	name: string,
	/**  `file`, `pay` or `file_and_pay`. */
	action: string,
	/**  `2026-09`, `2026-Q3` or `2025`. */
	period: string,
	/**  The date the rule gives. */
	nominal: string,
	/**  The deadline, after any shift. */
	due: string,
	/**  It moved past a weekend or holiday. */
	shifted: boolean,
	/**  Act and provision. */
	citation: string,
	/**  `past`, `next` or `upcoming`, against the as-of date. */
	status: string,
};

/**  A verified pack update. */
export type PackUpdateDto = {
	/**  The pack in use. */
	inUse: string,
	/**  The verified update. */
	installed: string,
	/**  For people. */
	message: string,
};

/**  One statutory value with its source. */
export type PackValueDto = {
	/**  Dotted key. */
	key: string,
	/**  `percent`, `amount`, `days`, `rounding`, `flag`. */
	kind: string,
	/**  As written in the pack. */
	value: string,
	/**  First day it applies. */
	effectiveFrom: string,
	/**  Last day, if it ends. */
	effectiveTo: string | null,
	/**  Act and provision. */
	citation: string,
	/**  Where to read the act. */
	url: string,
	/**  Context. */
	note: string | null,
};

/**  A period a screen can report on. */
export type PeriodChoiceDto = {
	/**  `2026-09`, `2026-Q3`, `2026-ytd`. */
	id: string,
	/**  `September 2026`, `Q3 2026`, `Apr – Sep 2026`. */
	label: string,
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
};

/**  An accounting period. */
export type PeriodDto = {
	/**  Row id. */
	id: number,
	/**  E.g. `Q3 2026`. */
	label: string,
	/**  First day. */
	startsOn: string,
	/**  Last day. */
	endsOn: string,
	/**  `open`, `closing` or `closed`. */
	state: string,
};

/**  Profit and loss. */
export type ProfitAndLossDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Revenue lines. */
	revenue: StatementLineDto[],
	/**  Expense lines. */
	expenses: StatementLineDto[],
	/**  Sum of revenue. */
	totalRevenue: MoneyDto,
	/**  Sum of expenses. */
	totalExpenses: MoneyDto,
	/**  Revenue minus expenses. */
	profit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  An inbox item. */
export type ProposalDto = {
	/**  Stable id. */
	id: string,
	/**  `posting`, `deadline`, `advice`, `reminder`. */
	kind: string,
	/**  One line. */
	title: string,
	/**  Second line. */
	detail: string,
	/**  `certain`, `likely`, `needs_you`. */
	confidence: string | null,
	/**  `rule`, `matcher`, `advisor`, `calendar`. */
	sourceKind: string,
	/**  Shown as the origin, e.g. `Rule “EU SaaS”`. */
	source: string,
	/**  The bank line it came from. */
	bankLineId: string | null,
	/**  For deadlines. */
	dueOn: string | null,
	/**  The headline amount, signed as the bank line. */
	amount: MoneyDto | null,
	/**  For postings. */
	entry: ProposedEntryDto | null,
	/**  Why. */
	reasons: string[],
};

/**  A journal entry proposed by a rule, the matcher or an advisor. */
export type ProposedEntryDto = {
	/**  Accounting date. */
	date: string,
	/**  Description. */
	memo: string,
	/**  The lines. */
	lines: ProposedLineDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits (positive). */
	totalCredit: MoneyDto,
	/**  Debits equal credits; the kernel re-checks on approval. */
	balanced: boolean,
};

/**  One line of a proposed entry, split into debit and credit for display. */
export type ProposedLineDto = {
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Debit, if this is a debit line. */
	debit: MoneyDto | null,
	/**  Credit, if this is a credit line. */
	credit: MoneyDto | null,
	/**  VAT code. */
	vatCode: string | null,
};

/**
 *  A received invoice as typed in the editor. The core checks it and
 *  computes the VAT.
 */
export type PurchaseDraftDto = {
	/**  The supplier's legal name. */
	supplier: string,
	/**  Their IČO. */
	ico: string | null,
	/**  Their DIČ; needed to deduct VAT. */
	dic: string | null,
	/**  The invoice's number, as the supplier printed it. */
	number: string,
	/**  Issued. */
	issueDate: string,
	/**  DUZP; the issue date when empty. */
	taxPointDate: string | null,
	/**  Due. */
	dueDate: string | null,
	/**  The lines. */
	lines: PurchaseLineDraftDto[],
	/**  The VAT the invoice states, to check against the computed VAT. */
	statedVat: string | null,
};

/**  A received invoice in the books. */
export type PurchaseDto = {
	/**  Its journal entry. */
	entryId: number,
	/**  The supplier's number. */
	number: string,
	/**  The supplier. */
	supplier: string,
	/**  Their DIČ. */
	dic: string | null,
	/**  The entry's date (the tax point). */
	issuedOn: string,
	/**  Due. */
	dueOn: string | null,
	/**  Without VAT. */
	base: MoneyDto,
	/**  VAT deducted. */
	vat: MoneyDto,
	/**  Owed in all. */
	gross: MoneyDto,
	/**  Paid so far. */
	paid: MoneyDto,
	/**  Still owed. */
	open: MoneyDto,
	/**  `open`, `overdue` or `paid`. */
	status: string,
	/**  Days past due, when overdue. */
	daysOverdue: number | null,
};

/**  What the purchase editor offers. */
export type PurchaseFormDto = {
	/**  Expense accounts. */
	accounts: AccountChoiceDto[],
	/**  Input-VAT codes; none when the books aren't VAT-registered. */
	vatCodes: VatCodeChoiceDto[],
	/**  Whether these books deduct VAT. */
	vatPayer: boolean,
	/**  Today. */
	today: string,
};

/**  One line of a received invoice as typed. */
export type PurchaseLineDraftDto = {
	/**  What it was for. */
	description: string,
	/**  The expense account. */
	account: string,
	/**  An input-VAT code, or none when no VAT is deducted. */
	vatCode: string | null,
	/**  The amount without VAT, in Czech format (`1 200,00`). */
	base: string,
};

/**  A recovery key to show once and have confirmed. */
export type RecoveryKeyDto = {
	/**  In groups of four, e.g. `ABCD-EFGH-…`. */
	key: string,
	/**  How many groups. */
	groups: number,
};

/**  A recurring invoice template. */
export type RecurringTemplateDto = {
	/**  Row id. */
	id: number,
	/**  For people. */
	name: string,
	/**  The customer. */
	client: string,
	/**  `weekly`, `monthly`, `quarterly` or `yearly`. */
	frequency: string,
	/**  Units between runs. */
	interval: number,
	/**  The first occurrence. */
	start: string,
	/**  The next occurrence, if the schedule hasn't ended. */
	next: string | null,
	/**  Days to the due date. */
	dueDays: number,
	/**  Issued automatically, or left as a draft. */
	autoIssue: boolean,
	/**  Paused templates don't run. */
	active: boolean,
	/**  Each invoice's total, with VAT, at today's pack rates. */
	gross: MoneyDto,
};

/**  Reference data and where it came from. */
export type RefDataDto = {
	/**  Whether the user allows fetching from the ČNB. */
	fetchEnabled: boolean,
	/**  The only host fetches go to. */
	fetchHost: string,
	/**  Days of exchange rates loaded. */
	fxDays: number,
	/**  Today's euro rate, when loaded. */
	euro: string | null,
	/**  Repo-rate changes loaded. */
	repoChanges: number,
	/**  The repo rate in force today, when loaded. */
	repoNow: string | null,
	/**  Every import or fetch, oldest first. */
	sources: RefSourceDto[],
	/**  Keys trusted to sign pack updates. */
	trustedKeys: number,
	/**  A verified pack update waiting for the next opening. */
	pendingPack: string | null,
};

/**  One import or fetch. */
export type RefSourceDto = {
	/**  `cnb_fx` or `cnb_repo`. */
	kind: string,
	/**  `imported <file>` or `fetched <url>`. */
	origin: string,
	/**  What it brought. */
	summary: string,
	/**  When. */
	on: string,
};

/**  What the screens report on, as of the books' date. */
export type ReportingPeriodsDto = {
	/**  The books' date. */
	today: string,
	/**  Its year, for the obligations calendar. */
	year: number,
	/**  Where the books begin. */
	booksFrom: string,
	/**
	 *  The last VAT periods that have ended, newest first; none when the
	 *  books aren't VAT-registered.
	 */
	vat: PeriodChoiceDto[],
	/**  Up to two ended quarters that overlap the books, oldest first. */
	quarters: PeriodChoiceDto[],
	/**  The last of them. */
	lastQuarter: PeriodChoiceDto | null,
	/**  The one before, to compare with. */
	priorQuarter: PeriodChoiceDto | null,
	/**  The last quarter's year up to its end (or the books so far). */
	yearToDate: PeriodChoiceDto,
};

/**  The rule pack in force. */
export type RulePackDto = {
	/**  `cz-2026@2026.1`. */
	provenance: string,
	/**  `draft` or `reviewed`. */
	review: string,
	/**  Scope. */
	summary: string,
	/**  What the pack leaves out, and why. */
	omitted: string[],
	/**  Values effective on the entity's as-of date. */
	values: PackValueDto[],
	/**  Public holidays it knows. */
	holidays: number,
};

/**  One weighted reason in a match score. */
export type ScoreContributionDto = {
	/**  Why. */
	reason: string,
	/**  Signed weight as written, e.g. `+.40`. */
	weight: string,
};

/**  Whether there are books to unlock. */
export type SessionStateDto = {
	/**  `needs_setup`, `locked`, `open` or `demo`. */
	state: string,
	/**  Whose books, when known. */
	entity: string | null,
	/**  The OS keychain holds the key, so unlocking needn't ask. */
	remembered: boolean,
};

/**  What a report read; see `skyla_ledger::Snapshot`. */
export type SnapshotDto = {
	/**  Posted entries read. */
	entries: number,
	/**  Highest posting sequence number read. */
	lastPostedSeq: number | null,
	/**  SHA-256 hex. */
	hash: string,
};

/**  A statement line by synthetic account. */
export type StatementLineDto = {
	/**  Account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  Amount as the statement reads. */
	amount: MoneyDto,
};

/**  The tax advisor's answer, checked against the engine. */
export type TaxAdviceDto = {
	/**  `accepted`, `rejected`, `needs_confirmation`, `blocked`, or how the run failed. */
	status: string,
	/**  The scenario it puts first, when accepted. */
	recommendation: string | null,
	/**  Its explanation, when accepted (every figure checked). */
	explanation: string | null,
	/**  Levers it considered. */
	levers: string[],
	/**  Facts it needs from the user. */
	questions: string[],
	/**  Why it was rejected or didn't run. */
	problems: string[],
	/**  Figures matched to engine values. */
	grounded: number,
	/**  The register entry. */
	runId: string | null,
	/**  The engine's scenarios it explains. */
	scenarios: TaxScenariosDto,
};

/**  The user's projection for the year, typed in the scenario form. */
export type TaxProjectionDto = {
	/**  § 7 income, e.g. `1 571 000`. */
	income: string,
	/**  Actual tax-deductible expenses. */
	expenses: string,
	/**  `craft`, `trade` or `liberal`; empty when unknown. */
	flatRate: string | null,
	/**  A planned purchase, for the timing lever (may be empty). */
	purchaseDescription: string,
	/**  Its price excluding claimable VAT (empty for none). */
	purchasePrice: string,
};

/**  One scenario's worksheet and its difference from the baseline. */
export type TaxScenarioDto = {
	/**  Stable id. */
	id: string,
	/**  For people. */
	label: string,
	/**  Expenses claimed. */
	expenses: MoneyDto,
	/**  The flat rate, when used (`60`). */
	flatRatePercent: string | null,
	/**  Its cap. */
	flatRateCap: MoneyDto | null,
	/**  The cap applied. */
	capped: boolean,
	/**  Income minus expenses. */
	profit: MoneyDto,
	/**  Rounded tax base. */
	taxBase: MoneyDto,
	/**  Rate (`15`). */
	taxRatePercent: string,
	/**  Tax before credits. */
	taxBeforeCredits: MoneyDto,
	/**  Taxpayer credit used. */
	taxpayerCredit: MoneyDto,
	/**  Income tax. */
	tax: MoneyDto,
	/**  Social insurance assessment base (also the pension base). */
	socialBase: MoneyDto,
	/**  Its rate. */
	socialRatePercent: string,
	/**  Social insurance. */
	social: MoneyDto,
	/**  Health insurance assessment base. */
	healthBase: MoneyDto,
	/**  Its rate. */
	healthRatePercent: string,
	/**  Health insurance. */
	health: MoneyDto,
	/**  Tax and insurance. */
	total: MoneyDto,
	/**  Tax against the baseline. */
	vsBaselineTax: MoneyDto,
	/**  Both insurances against the baseline. */
	vsBaselineInsurance: MoneyDto,
	/**  Everything against the baseline. */
	vsBaselineTotal: MoneyDto,
	/**  The pension assessment base against the baseline. */
	vsBaselinePensionBase: MoneyDto,
};

/**  The § 7 scenarios for the year. */
export type TaxScenariosDto = {
	/**  The tax year. */
	year: string,
	/**  `books` (cash basis so far) or `projection`. */
	source: string,
	/**  First day covered. */
	from: string,
	/**  Last day covered. */
	to: string,
	/**  § 7 income. */
	income: MoneyDto,
	/**  Actual expenses. */
	actualExpenses: MoneyDto,
	/**  The flat-rate group, when known. */
	flatRate: string | null,
	/**  The scenario the others are compared with. */
	baseline: string,
	/**  The scenario with the lowest tax and insurance. */
	lowestTotal: string,
	/**  Every combination. */
	scenarios: TaxScenarioDto[],
	/**  Facts that would change the analysis. */
	questions: string[],
	/**  Levers that couldn't be evaluated, and why. */
	notEvaluated: string[],
	/**  What the computation assumed. */
	assumptions: string[],
	/**  Pack provenance. */
	pack: string,
};

/**  Trial balance. */
export type TrialBalanceDto = {
	/**  First day, or none for everything up to `to`. */
	from: string | null,
	/**  Last day. */
	to: string,
	/**  Rows by code. */
	rows: TrialBalanceRowDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits. */
	totalCredit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A trial-balance row. */
export type TrialBalanceRowDto = {
	/**  Leaf account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  `asset`, `liability`, `equity`, `revenue`, `expense`, `closing`. */
	kind: string,
	/**  Debits. */
	debit: MoneyDto,
	/**  Credits (positive). */
	credit: MoneyDto,
	/**  Debit minus credit. */
	balance: MoneyDto,
};

/**  A newer release. */
export type UpdateDto = {
	/**  Its version. */
	version: string,
	/**  When it was published. */
	published: string,
	/**  What changed, briefly. */
	notes: string,
	/**  Its release page. */
	page: string,
};

/**  The opt-in update check. */
export type UpdateStatusDto = {
	/**  Whether the user turned it on. */
	enabled: boolean,
	/**  This build's version. */
	current: string,
	/**  The only host it asks. */
	source: string,
	/**  Release keys this build trusts; none means no check is made. */
	trustedKeys: number,
	/**  Whether a check ran since it was turned on. */
	checked: boolean,
	/**  A newer release, if the last check found one. */
	available: UpdateDto | null,
};

/**  A VAT code the editor offers. */
export type VatCodeChoiceDto = {
	/**  The code. */
	code: string,
	/**  What it means. */
	name: string,
	/**  The rate today, e.g. `21`. */
	ratePercent: string,
};

/**  A DPH return for one period, computed from the ledger with the rule pack. */
export type VatReturnDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  The pack that mapped it, `cz-2026@2026.1`. */
	pack: string,
	/**  `draft` or `reviewed`. */
	packReview: string,
	/**  Rows in form order. */
	rows: VatReturnRowDto[],
	/**  Tax due on supplies and reverse charges. */
	outputTax: MoneyDto,
	/**  Tax claimed. */
	inputTax: MoneyDto,
	/**  Output minus input: positive to pay, negative for an excess deduction. */
	payable: MoneyDto,
	/**  VAT codes posted but not mapped; the return isn't complete while any exist. */
	unmapped: string[],
	/**  Filing and payment deadline (shifted to a working day). */
	dueOn: string,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  One row of the DPH return. */
export type VatReturnRowDto = {
	/**  Row as printed on the form. */
	row: string,
	/**  What feeds it. */
	label: string,
	/**  `output` (tax due) or `input` (tax claimed). */
	side: string,
	/**  Tax base. */
	base: MoneyDto,
	/**  Tax. */
	tax: MoneyDto,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

