// Generated by tauri-specta from apps/desktop/src-tauri (`just bindings`). Don't edit.
// biome-ignore-all lint: generated
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Build information. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  The open entity. */
	entity: () => __TAURI_INVOKE<EntityDto>("entity"),
	/**  Accounting periods. */
	periods: () => typedError<PeriodDto[], IpcFailure>(__TAURI_INVOKE("periods")),
	/**  Profit and loss for a date range. */
	profitAndLoss: (from: string, to: string) => typedError<ProfitAndLossDto, IpcFailure>(__TAURI_INVOKE("profit_and_loss", { from, to })),
	/**  Balance sheet as of a date. */
	balanceSheet: (asOf: string) => typedError<BalanceSheetDto, IpcFailure>(__TAURI_INVOKE("balance_sheet", { asOf })),
	/**  Trial balance. */
	trialBalance: (from: string | null, to: string) => typedError<TrialBalanceDto, IpcFailure>(__TAURI_INVOKE("trial_balance", { from, to })),
	/**  Cash basis (*daňová evidence*) for a date range. */
	cashBasis: (from: string, to: string) => typedError<CashBasisDto, IpcFailure>(__TAURI_INVOKE("cash_basis", { from, to })),
	/**  Posted journal entries in a date range. */
	journal: (from: string, to: string) => typedError<JournalEntryDto[], IpcFailure>(__TAURI_INVOKE("journal", { from, to })),
	/**  Hash chain and balance, for the status line. */
	integrity: () => typedError<IntegrityDto, IpcFailure>(__TAURI_INVOKE("integrity")),
	/**  Invoices. */
	invoices: () => typedError<InvoiceDto[], IpcFailure>(__TAURI_INVOKE("invoices")),
	/**  The latest bank import with its tie-out. */
	bankStatement: () => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("bank_statement")),
	/**  The inbox. */
	proposals: () => typedError<ProposalDto[], IpcFailure>(__TAURI_INVOKE("proposals")),
	/**  The egress register. */
	egressRegister: () => __TAURI_INVOKE<EgressRunDto[]>("egress_register"),
	/**  The DPH return for a period, mapped by the rule pack. */
	vatReturn: (from: string, to: string) => typedError<VatReturnDto, IpcFailure>(__TAURI_INVOKE("vat_return", { from, to })),
	/**  The rule pack in force, with citations. */
	rulePack: () => __TAURI_INVOKE<RulePackDto>("rule_pack"),
	/**  A document rendered to PDF (`cs` or `en`), base64-encoded. */
	invoicePdf: (id: number, lang: string) => typedError<DocumentPdfDto, IpcFailure>(__TAURI_INVOKE("invoice_pdf", { id, lang })),
	/**  An issued document as XML: `isdoc`, `ubl` (Peppol BIS 3.0) or `cii`. */
	invoiceXml: (id: number, format: string) => typedError<DocumentXmlDto, IpcFailure>(__TAURI_INVOKE("invoice_xml", { id, format })),
	/**  Reminders due on a date, drafted for the user to send. */
	dunningQueue: (asOf: string) => typedError<DunningNoticeDto[], IpcFailure>(__TAURI_INVOKE("dunning_queue", { asOf })),
	/**  Recurring invoice templates and their next runs. */
	recurringTemplates: () => typedError<RecurringTemplateDto[], IpcFailure>(__TAURI_INVOKE("recurring_templates")),
	/**  What the invoice editor offers. */
	invoiceForm: () => typedError<InvoiceFormDto, IpcFailure>(__TAURI_INVOKE("invoice_form")),
	/**  Saves a draft typed in the editor; the core parses and checks it. */
	createInvoiceDraft: (draft: InvoiceDraftDto) => typedError<InvoiceDto, IpcFailure>(__TAURI_INVOKE("create_invoice_draft", { draft })),
	/**  Issues a draft: the next number, posted through the kernel. */
	issueInvoice: (id: number, issueDate: string) => typedError<InvoiceDto, IpcFailure>(__TAURI_INVOKE("issue_invoice", { id, issueDate })),
	/**  Deletes a draft. */
	deleteInvoiceDraft: (id: number) => typedError<null, IpcFailure>(__TAURI_INVOKE("delete_invoice_draft", { id })),
};

/* Types */
/**  Build information. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Core version. */
	version: string,
};

/**  Balance sheet. */
export type BalanceSheetDto = {
	/**  The date. */
	asOf: string,
	/**  Asset lines. */
	assets: StatementLineDto[],
	/**  Liability lines. */
	liabilities: StatementLineDto[],
	/**  Equity lines. */
	equity: StatementLineDto[],
	/**  Profit not yet closed into equity. */
	unclosedProfit: MoneyDto,
	/**  Sum of assets. */
	totalAssets: MoneyDto,
	/**  Sum of liabilities. */
	totalLiabilities: MoneyDto,
	/**  Equity including the unclosed profit. */
	totalEquity: MoneyDto,
	/**  Assets equal liabilities plus equity. */
	balances: boolean,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A bank statement line. */
export type BankLineDto = {
	/**  Stable id. */
	id: string,
	/**  Booking date. */
	date: string,
	/**  Who. */
	counterparty: string,
	/**  VS, card or other reference. */
	reference: string,
	/**  Signed amount in the account currency. */
	amount: MoneyDto,
	/**  The original foreign amount, for card payments abroad. */
	foreign: ForeignAmountDto | null,
	/**  `open` or `matched`. */
	status: string,
	/**  What it was matched to. */
	matchedTo: string | null,
	/**  The proposal for this line. */
	proposalId: string | null,
	/**  Ranked candidates. */
	candidates: MatchCandidateDto[],
};

/**  An imported statement with its tie-out. */
export type BankStatementDto = {
	/**  Bank account label. */
	accountName: string,
	/**  Imported file. */
	file: string,
	/**  `CAMT.053`, `MT940`, `ABO`, `CSV`. */
	format: string,
	/**  First booking day. */
	from: string,
	/**  Last booking day. */
	to: string,
	/**  The ledger's balance before the statement. */
	opening: MoneyDto,
	/**  Sum of incoming lines. */
	credits: MoneyDto,
	/**  Sum of outgoing lines (negative). */
	debits: MoneyDto,
	/**  Opening plus every line. */
	closing: MoneyDto,
	/**  The closing balance the bank reported. */
	reportedClosing: MoneyDto,
	/**  `closing == reported_closing`. */
	tiesOut: boolean,
	/**  The lines, newest first. */
	lines: BankLineDto[],
};

/**  Cash basis (*daňová evidence*). */
export type CashBasisDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Every recognition. */
	lines: CashBasisLineDto[],
	/**  Totals per direction and treatment. */
	totals: CashBasisTotalDto[],
	/**  Taxable income. */
	taxableIncome: MoneyDto,
	/**  Deductible expenses. */
	deductibleExpenses: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A cash-basis recognition. */
export type CashBasisLineDto = {
	/**  Payment date. */
	date: string,
	/**  The payment entry. */
	cashEntryId: number,
	/**  The settled entry, if any. */
	settledEntryId: number | null,
	/**  Revenue or expense account. */
	account: string,
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The recognised amount. */
	amount: MoneyDto,
};

/**  A cash-basis total. */
export type CashBasisTotalDto = {
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The total. */
	amount: MoneyDto,
};

/**  A customer. */
export type ClientDto = {
	/**  Legal name. */
	name: string,
	/**  IČO. */
	ico: string | null,
	/**  DIČ. */
	dic: string | null,
	/**  Postal address. */
	address: string | null,
};

/**  A rendered document, ready to save or open. */
export type DocumentPdfDto = {
	/**  Suggested file name, e.g. `Faktura 2026-041.pdf`. */
	fileName: string,
	/**  The PDF, base64-encoded. */
	pdfBase64: string,
	/**  Pages in the PDF. */
	pages: number,
	/**  The QR Platba payload, if the document asks for a payment. */
	spayd: string | null,
};

/**  A document written in an exchange format (ISDOC, UBL, CII). */
export type DocumentXmlDto = {
	/**  Suggested file name, e.g. `2026-041.isdoc`. */
	fileName: string,
	/**  The file's media type. */
	mediaType: string,
	/**  The XML. */
	xml: string,
};

/**  A reminder that is due, drafted for the user to send. */
export type DunningNoticeDto = {
	/**  The invoice. */
	documentId: number,
	/**  Its number. */
	number: string,
	/**  Who owes. */
	customer: string,
	/**  The step, from 1. */
	step: number,
	/**  `friendly`, `firm` or `final`. */
	tone: string,
	/**  When the invoice was due. */
	dueOn: string,
	/**  When this step became due. */
	scheduledOn: string,
	/**  Days past due. */
	daysOverdue: number,
	/**  Still owed. */
	open: MoneyDto,
	/**  The late interest stated on the final step. */
	interest: LateInterestDto | null,
	/**  Why the interest is missing (no ČNB rate history imported). */
	interestProblem: string | null,
	/**  Draft subject, Czech. */
	subjectCs: string,
	/**  Draft body, Czech. */
	bodyCs: string,
	/**  Draft subject, English. */
	subjectEn: string,
	/**  Draft body, English. */
	bodyEn: string,
};

/**  One run in the egress register. */
export type EgressRunDto = {
	/**  Stable id. */
	id: string,
	/**  RFC 3339 UTC. */
	at: string,
	/**  Which advisor. */
	advisor: string,
	/**  What for. */
	purpose: string,
	/**  The provider, e.g. the user's Claude Code installation. */
	provider: string,
	/**  The model setting used. */
	model: string,
	/**  What left the machine, summarised. */
	sent: string,
	/**  Fields removed by the egress gate. */
	redacted: string[],
	/**  MCP tool calls answered. */
	toolCalls: number,
	/**  Bytes sent, prompts and tool results together. */
	bytesSent: number,
	/**  What came of it. */
	outcome: string,
};

/**  The open entity. */
export type EntityDto = {
	/**  Shown in the source list. */
	displayName: string,
	/**  `OSVČ` or `s.r.o.`. */
	legalForm: string,
	/**  `monthly`, `quarterly` or `non-payer`. */
	vatPeriod: string,
	/**  ISO 4217. */
	functionalCurrency: string,
	/**  The date the books are seen from (today, or the demo's fixed date). */
	asOf: string,
	/**  Bank account label, masked. */
	bankName: string,
};

/**  A foreign-currency amount behind a bank line. */
export type ForeignAmountDto = {
	/**  The original amount. */
	amount: MoneyDto,
	/**  The conversion rate. */
	rate: string,
};

/**  Journal integrity for the status line. */
export type IntegrityDto = {
	/**  Every posted entry fits the hash chain. */
	chainIntact: boolean,
	/**  Posted entries verified. */
	entriesChecked: number,
	/**  The verified chain head. */
	head: string | null,
	/**  The first break, described, if any. */
	firstBreak: string | null,
	/**  Debits equal credits across the journal. */
	balanced: boolean,
};

/**  A stretch of delay at a constant principal. */
export type InterestPeriodDto = {
	/**  First day. */
	from: string,
	/**  Last day, inclusive. */
	to: string,
	/**  Days. */
	days: number,
	/**  What was owed. */
	principal: MoneyDto,
	/**  Interest. */
	interest: MoneyDto,
};

/**  A draft invoice as typed in the editor. The core parses and checks it. */
export type InvoiceDraftDto = {
	/**  A customer's legal name, as [`InvoiceFormDto::clients`] lists them. */
	client: string,
	/**  Days from today to the due date. */
	dueDays: number,
	/**  Free text printed on the invoice. */
	note: string,
	/**  The lines. */
	lines: InvoiceDraftLineDto[],
};

/**  A line as typed: Czech number formats (`1,5`, `1 200,00`). */
export type InvoiceDraftLineDto = {
	/**  What was supplied. */
	description: string,
	/**  Quantity, e.g. `21` or `1,5`. */
	quantity: string,
	/**  Unit, e.g. `h`. */
	unit: string,
	/**  Price per unit excluding VAT, e.g. `1 200,00`. */
	unitPrice: string,
	/**  One of [`InvoiceFormDto::vat_codes`]. */
	vatCode: string,
};

/**  An issued (or drafted) invoice. */
export type InvoiceDto = {
	/**  Document id. */
	id: number,
	/**  Invoice number, once issued. */
	number: string | null,
	/**  Client name. */
	client: string,
	/**  `draft`, `scheduled`, `open`, `overdue`, `partPaid`, `paid`, `credited`. */
	status: string,
	/**  Issue date (posted invoices). */
	issuedOn: string | null,
	/**  Due date. */
	dueOn: string | null,
	/**  When a scheduled invoice will be issued. */
	scheduledFor: string | null,
	/**  When it was paid in full. */
	paidOn: string | null,
	/**  Days past due, when overdue and open. */
	daysOverdue: number | null,
	/**  Excluding VAT. */
	base: MoneyDto,
	/**  VAT. */
	vat: MoneyDto,
	/**  Total. */
	gross: MoneyDto,
	/**  Paid so far. */
	paid: MoneyDto,
	/**  Credited by credit notes. */
	credited: MoneyDto,
	/**  Still open. */
	open: MoneyDto,
	/**  The lines. */
	lines: InvoiceLineDto[],
	/**  The posted journal entry, if issued. */
	entryId: number | null,
	/**  The rule pack its totals were fixed with, once issued. */
	pack: string | null,
};

/**  What the invoice editor offers. */
export type InvoiceFormDto = {
	/**  Customers seen on earlier documents. */
	clients: ClientDto[],
	/**  The VAT codes this supplier may put on a sale. */
	vatCodes: VatCodeChoiceDto[],
	/**  Units the line editor suggests. */
	units: string[],
	/**  Payment terms the editor offers, in days. */
	dueDays: number[],
	/**  Today: the issue date a draft issued now gets. */
	today: string,
	/**  The number the next invoice issued today gets. */
	nextNumber: string,
};

/**  One invoice line. */
export type InvoiceLineDto = {
	/**  What was supplied. */
	description: string,
	/**  Quantity as written, e.g. `56`. */
	quantity: string,
	/**  Unit, e.g. `h`. */
	unit: string,
	/**  Price per unit, excluding VAT. */
	unitPrice: MoneyDto,
	/**  The rule pack's VAT code. */
	vatCode: string,
	/**  Its rate in percent on the document date, from the rule pack. */
	vatRatePercent: string,
	/**  Quantity × unit price. */
	base: MoneyDto,
	/**  VAT on the line. */
	vat: MoneyDto,
};

/**
 *  The error every command returns to the webview: a stable code and a
 *  message for people.
 */
export type IpcFailure = {
	/**  `ledger`, `bad_request`, `demo`, `out_of_range`, `money`. */
	code: string,
	/**  What went wrong. */
	message: string,
};

/**  A posted journal entry. */
export type JournalEntryDto = {
	/**  Row id. */
	id: number,
	/**  Accounting date. */
	date: string,
	/**  Gapless posting number. */
	postedSeq: number | null,
	/**  `manual`, `invoice`, `bank`, `rule`, `advisor`, `reversal`, `opening`. */
	sourceKind: string,
	/**  Origin reference. */
	sourceRef: string | null,
	/**  Description. */
	memo: string,
	/**  Approver, when recorded. */
	approvedBy: string | null,
	/**  The entry it reverses. */
	reversesId: number | null,
	/**  The lines. */
	lines: JournalLineDto[],
};

/**  A journal line. */
export type JournalLineDto = {
	/**  One-based. */
	lineNo: number,
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Amount in the line's currency; debit positive. */
	amount: MoneyDto,
	/**  Functional-currency amount. */
	functional: MoneyDto,
	/**  FX rate for foreign lines. */
	fxRate: string | null,
	/**  VAT code. */
	vatCode: string | null,
	/**  Free text. */
	memo: string,
};

/**  Statutory late interest on one receivable. */
export type LateInterestDto = {
	/**  The first day of delay. */
	delayFrom: string,
	/**  The half-year start whose ČNB repo rate applies. */
	rateDate: string,
	/**  Annual percent, e.g. `11.5`. */
	annualRate: string,
	/**  One period per stretch at a constant principal. */
	periods: InterestPeriodDto[],
	/**  Sum of the periods. */
	total: MoneyDto,
	/**  The statutory minimum recovery cost. */
	recoveryCost: MoneyDto,
};

/**  A candidate document for a bank line. */
export type MatchCandidateDto = {
	/**  E.g. `Invoice 2026-102 · Studio Brno`. */
	label: string,
	/**  Key facts. */
	detail: string,
	/**  `0.96`. */
	score: string,
	/**  `certain`, `likely`, `needs_you`, `unlikely`. */
	confidence: string,
	/**  The score as a sum of named contributions. */
	contributions: ScoreContributionDto[],
};

/**  An amount in integer minor units (`8470000` CZK is 84 700,00 Kč). */
export type MoneyDto = {
	/**  Minor units; always within ±(2^53 − 1). */
	minor: number,
	/**  ISO 4217 code. */
	currency: string,
};

/**  One statutory value with its source. */
export type PackValueDto = {
	/**  Dotted key. */
	key: string,
	/**  `percent`, `amount`, `days`, `rounding`, `flag`. */
	kind: string,
	/**  As written in the pack. */
	value: string,
	/**  First day it applies. */
	effectiveFrom: string,
	/**  Last day, if it ends. */
	effectiveTo: string | null,
	/**  Act and provision. */
	citation: string,
	/**  Where to read the act. */
	url: string,
	/**  Context. */
	note: string | null,
};

/**  An accounting period. */
export type PeriodDto = {
	/**  Row id. */
	id: number,
	/**  E.g. `Q3 2026`. */
	label: string,
	/**  First day. */
	startsOn: string,
	/**  Last day. */
	endsOn: string,
	/**  `open`, `closing` or `closed`. */
	state: string,
};

/**  Profit and loss. */
export type ProfitAndLossDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Revenue lines. */
	revenue: StatementLineDto[],
	/**  Expense lines. */
	expenses: StatementLineDto[],
	/**  Sum of revenue. */
	totalRevenue: MoneyDto,
	/**  Sum of expenses. */
	totalExpenses: MoneyDto,
	/**  Revenue minus expenses. */
	profit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  An inbox item. */
export type ProposalDto = {
	/**  Stable id. */
	id: string,
	/**  `posting`, `deadline`, `advice`, `reminder`. */
	kind: string,
	/**  One line. */
	title: string,
	/**  Second line. */
	detail: string,
	/**  `certain`, `likely`, `needs_you`. */
	confidence: string | null,
	/**  `rule`, `matcher`, `advisor`, `calendar`. */
	sourceKind: string,
	/**  Shown as the origin, e.g. `Rule “EU SaaS”`. */
	source: string,
	/**  The bank line it came from. */
	bankLineId: string | null,
	/**  For deadlines. */
	dueOn: string | null,
	/**  The headline amount, signed as the bank line. */
	amount: MoneyDto | null,
	/**  For postings. */
	entry: ProposedEntryDto | null,
	/**  Why. */
	reasons: string[],
};

/**  A journal entry proposed by a rule, the matcher or an advisor. */
export type ProposedEntryDto = {
	/**  Accounting date. */
	date: string,
	/**  Description. */
	memo: string,
	/**  The lines. */
	lines: ProposedLineDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits (positive). */
	totalCredit: MoneyDto,
	/**  Debits equal credits; the kernel re-checks on approval. */
	balanced: boolean,
};

/**  One line of a proposed entry, split into debit and credit for display. */
export type ProposedLineDto = {
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Debit, if this is a debit line. */
	debit: MoneyDto | null,
	/**  Credit, if this is a credit line. */
	credit: MoneyDto | null,
	/**  VAT code. */
	vatCode: string | null,
};

/**  A recurring invoice template. */
export type RecurringTemplateDto = {
	/**  Row id. */
	id: number,
	/**  For people. */
	name: string,
	/**  The customer. */
	client: string,
	/**  `weekly`, `monthly`, `quarterly` or `yearly`. */
	frequency: string,
	/**  Units between runs. */
	interval: number,
	/**  The first occurrence. */
	start: string,
	/**  The next occurrence, if the schedule hasn't ended. */
	next: string | null,
	/**  Days to the due date. */
	dueDays: number,
	/**  Issued automatically, or left as a draft. */
	autoIssue: boolean,
	/**  Paused templates don't run. */
	active: boolean,
	/**  Each invoice's total, with VAT, at today's pack rates. */
	gross: MoneyDto,
};

/**  The rule pack in force. */
export type RulePackDto = {
	/**  `cz-2026@2026.1`. */
	provenance: string,
	/**  `draft` or `reviewed`. */
	review: string,
	/**  Scope. */
	summary: string,
	/**  What the pack leaves out, and why. */
	omitted: string[],
	/**  Values effective on the entity's as-of date. */
	values: PackValueDto[],
	/**  Public holidays it knows. */
	holidays: number,
};

/**  One weighted reason in a match score. */
export type ScoreContributionDto = {
	/**  Why. */
	reason: string,
	/**  Signed weight as written, e.g. `+.40`. */
	weight: string,
};

/**  What a report read; see `skyla_ledger::Snapshot`. */
export type SnapshotDto = {
	/**  Posted entries read. */
	entries: number,
	/**  Highest posting sequence number read. */
	lastPostedSeq: number | null,
	/**  SHA-256 hex. */
	hash: string,
};

/**  A statement line by synthetic account. */
export type StatementLineDto = {
	/**  Account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  Amount as the statement reads. */
	amount: MoneyDto,
};

/**  Trial balance. */
export type TrialBalanceDto = {
	/**  First day, or none for everything up to `to`. */
	from: string | null,
	/**  Last day. */
	to: string,
	/**  Rows by code. */
	rows: TrialBalanceRowDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits. */
	totalCredit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A trial-balance row. */
export type TrialBalanceRowDto = {
	/**  Leaf account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  `asset`, `liability`, `equity`, `revenue`, `expense`, `closing`. */
	kind: string,
	/**  Debits. */
	debit: MoneyDto,
	/**  Credits (positive). */
	credit: MoneyDto,
	/**  Debit minus credit. */
	balance: MoneyDto,
};

/**  A VAT code the editor offers. */
export type VatCodeChoiceDto = {
	/**  The code. */
	code: string,
	/**  What it means. */
	name: string,
	/**  The rate today, e.g. `21`. */
	ratePercent: string,
};

/**  A DPH return for one period, computed from the ledger with the rule pack. */
export type VatReturnDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  The pack that mapped it, `cz-2026@2026.1`. */
	pack: string,
	/**  `draft` or `reviewed`. */
	packReview: string,
	/**  Rows in form order. */
	rows: VatReturnRowDto[],
	/**  Tax due on supplies and reverse charges. */
	outputTax: MoneyDto,
	/**  Tax claimed. */
	inputTax: MoneyDto,
	/**  Output minus input: positive to pay, negative for an excess deduction. */
	payable: MoneyDto,
	/**  VAT codes posted but not mapped; the return isn't complete while any exist. */
	unmapped: string[],
	/**  Filing and payment deadline (shifted to a working day). */
	dueOn: string,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  One row of the DPH return. */
export type VatReturnRowDto = {
	/**  Row as printed on the form. */
	row: string,
	/**  What feeds it. */
	label: string,
	/**  `output` (tax due) or `input` (tax claimed). */
	side: string,
	/**  Tax base. */
	base: MoneyDto,
	/**  Tax. */
	tax: MoneyDto,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

