// Generated by tauri-specta from apps/desktop/src-tauri (`just bindings`). Don't edit.
// biome-ignore-all lint: generated
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Build information. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  The open entity. */
	entity: () => __TAURI_INVOKE<EntityDto>("entity"),
	/**  Accounting periods. */
	periods: () => typedError<PeriodDto[], IpcFailure>(__TAURI_INVOKE("periods")),
	/**  Profit and loss for a date range. */
	profitAndLoss: (from: string, to: string) => typedError<ProfitAndLossDto, IpcFailure>(__TAURI_INVOKE("profit_and_loss", { from, to })),
	/**  Balance sheet as of a date. */
	balanceSheet: (asOf: string) => typedError<BalanceSheetDto, IpcFailure>(__TAURI_INVOKE("balance_sheet", { asOf })),
	/**  Trial balance. */
	trialBalance: (from: string | null, to: string) => typedError<TrialBalanceDto, IpcFailure>(__TAURI_INVOKE("trial_balance", { from, to })),
	/**  Cash basis (*daňová evidence*) for a date range. */
	cashBasis: (from: string, to: string) => typedError<CashBasisDto, IpcFailure>(__TAURI_INVOKE("cash_basis", { from, to })),
	/**  Posted journal entries in a date range. */
	journal: (from: string, to: string) => typedError<JournalEntryDto[], IpcFailure>(__TAURI_INVOKE("journal", { from, to })),
	/**  Hash chain and balance, for the status line. */
	integrity: () => typedError<IntegrityDto, IpcFailure>(__TAURI_INVOKE("integrity")),
	/**  Invoices. */
	invoices: () => typedError<InvoiceDto[], IpcFailure>(__TAURI_INVOKE("invoices")),
	/**  The latest bank import with its tie-out. */
	bankStatement: () => typedError<BankStatementDto, IpcFailure>(__TAURI_INVOKE("bank_statement")),
	/**  The inbox. */
	proposals: () => typedError<ProposalDto[], IpcFailure>(__TAURI_INVOKE("proposals")),
	/**  The egress register. */
	egressRegister: () => __TAURI_INVOKE<EgressRunDto[]>("egress_register"),
};

/* Types */
/**  Build information. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Core version. */
	version: string,
};

/**  Balance sheet. */
export type BalanceSheetDto = {
	/**  The date. */
	asOf: string,
	/**  Asset lines. */
	assets: StatementLineDto[],
	/**  Liability lines. */
	liabilities: StatementLineDto[],
	/**  Equity lines. */
	equity: StatementLineDto[],
	/**  Profit not yet closed into equity. */
	unclosedProfit: MoneyDto,
	/**  Sum of assets. */
	totalAssets: MoneyDto,
	/**  Sum of liabilities. */
	totalLiabilities: MoneyDto,
	/**  Equity including the unclosed profit. */
	totalEquity: MoneyDto,
	/**  Assets equal liabilities plus equity. */
	balances: boolean,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A bank statement line. */
export type BankLineDto = {
	/**  Stable id. */
	id: string,
	/**  Booking date. */
	date: string,
	/**  Who. */
	counterparty: string,
	/**  VS, card or other reference. */
	reference: string,
	/**  Signed amount in the account currency. */
	amount: MoneyDto,
	/**  The original foreign amount, for card payments abroad. */
	foreign: ForeignAmountDto | null,
	/**  `open` or `matched`. */
	status: string,
	/**  What it was matched to. */
	matchedTo: string | null,
	/**  The proposal for this line. */
	proposalId: string | null,
	/**  Ranked candidates. */
	candidates: MatchCandidateDto[],
};

/**  An imported statement with its tie-out. */
export type BankStatementDto = {
	/**  Bank account label. */
	accountName: string,
	/**  Imported file. */
	file: string,
	/**  `CAMT.053`, `MT940`, `ABO`, `CSV`. */
	format: string,
	/**  First booking day. */
	from: string,
	/**  Last booking day. */
	to: string,
	/**  The ledger's balance before the statement. */
	opening: MoneyDto,
	/**  Sum of incoming lines. */
	credits: MoneyDto,
	/**  Sum of outgoing lines (negative). */
	debits: MoneyDto,
	/**  Opening plus every line. */
	closing: MoneyDto,
	/**  The closing balance the bank reported. */
	reportedClosing: MoneyDto,
	/**  `closing == reported_closing`. */
	tiesOut: boolean,
	/**  The lines, newest first. */
	lines: BankLineDto[],
};

/**  Cash basis (*daňová evidence*). */
export type CashBasisDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Every recognition. */
	lines: CashBasisLineDto[],
	/**  Totals per direction and treatment. */
	totals: CashBasisTotalDto[],
	/**  Taxable income. */
	taxableIncome: MoneyDto,
	/**  Deductible expenses. */
	deductibleExpenses: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A cash-basis recognition. */
export type CashBasisLineDto = {
	/**  Payment date. */
	date: string,
	/**  The payment entry. */
	cashEntryId: number,
	/**  The settled entry, if any. */
	settledEntryId: number | null,
	/**  Revenue or expense account. */
	account: string,
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The recognised amount. */
	amount: MoneyDto,
};

/**  A cash-basis total. */
export type CashBasisTotalDto = {
	/**  `income` or `expense`. */
	direction: string,
	/**  Income-tax treatment. */
	taxTreatment: string,
	/**  The total. */
	amount: MoneyDto,
};

/**  One run in the egress register. */
export type EgressRunDto = {
	/**  Stable id. */
	id: string,
	/**  RFC 3339 UTC. */
	at: string,
	/**  Which advisor. */
	advisor: string,
	/**  What for. */
	purpose: string,
	/**  The provider, e.g. the user's Claude Code installation. */
	provider: string,
	/**  The model setting used. */
	model: string,
	/**  What left the machine, summarised. */
	sent: string,
	/**  Fields removed by the egress gate. */
	redacted: string[],
	/**  MCP tool calls answered. */
	toolCalls: number,
	/**  Bytes sent, prompts and tool results together. */
	bytesSent: number,
	/**  What came of it. */
	outcome: string,
};

/**  The open entity. */
export type EntityDto = {
	/**  Shown in the source list. */
	displayName: string,
	/**  `OSVČ` or `s.r.o.`. */
	legalForm: string,
	/**  `monthly`, `quarterly` or `non-payer`. */
	vatPeriod: string,
	/**  ISO 4217. */
	functionalCurrency: string,
	/**  The date the books are seen from (today, or the demo's fixed date). */
	asOf: string,
	/**  Bank account label, masked. */
	bankName: string,
};

/**  A foreign-currency amount behind a bank line. */
export type ForeignAmountDto = {
	/**  The original amount. */
	amount: MoneyDto,
	/**  The conversion rate. */
	rate: string,
};

/**  Journal integrity for the status line. */
export type IntegrityDto = {
	/**  Every posted entry fits the hash chain. */
	chainIntact: boolean,
	/**  Posted entries verified. */
	entriesChecked: number,
	/**  The verified chain head. */
	head: string | null,
	/**  The first break, described, if any. */
	firstBreak: string | null,
	/**  Debits equal credits across the journal. */
	balanced: boolean,
};

/**  An issued (or drafted) invoice. */
export type InvoiceDto = {
	/**  Invoice number. */
	number: string,
	/**  Client name. */
	client: string,
	/**  `draft`, `scheduled`, `open`, `overdue`, `partPaid`, `paid`. */
	status: string,
	/**  Issue date (posted invoices). */
	issuedOn: string | null,
	/**  Due date. */
	dueOn: string | null,
	/**  When a scheduled invoice will be issued. */
	scheduledFor: string | null,
	/**  When it was paid in full. */
	paidOn: string | null,
	/**  Days past due, when overdue and open. */
	daysOverdue: number | null,
	/**  Excluding VAT. */
	base: MoneyDto,
	/**  VAT. */
	vat: MoneyDto,
	/**  Total. */
	gross: MoneyDto,
	/**  Settled so far. */
	paid: MoneyDto,
	/**  Still open. */
	open: MoneyDto,
	/**  The lines. */
	lines: InvoiceLineDto[],
	/**  The posted journal entry, if issued. */
	entryId: number | null,
};

/**  One invoice line. */
export type InvoiceLineDto = {
	/**  What was supplied. */
	description: string,
	/**  Quantity as written, e.g. `56`. */
	quantity: string,
	/**  Unit, e.g. `h`. */
	unit: string,
	/**  Price per unit, excluding VAT. */
	unitPrice: MoneyDto,
	/**  VAT rate in percent, from the rule pack. */
	vatRatePercent: string,
	/**  Quantity × unit price. */
	base: MoneyDto,
	/**  VAT on the line. */
	vat: MoneyDto,
};

/**
 *  The error every command returns to the webview: a stable code and a
 *  message for people.
 */
export type IpcFailure = {
	/**  `ledger`, `bad_request`, `demo`, `out_of_range`, `money`. */
	code: string,
	/**  What went wrong. */
	message: string,
};

/**  A posted journal entry. */
export type JournalEntryDto = {
	/**  Row id. */
	id: number,
	/**  Accounting date. */
	date: string,
	/**  Gapless posting number. */
	postedSeq: number | null,
	/**  `manual`, `invoice`, `bank`, `rule`, `advisor`, `reversal`, `opening`. */
	sourceKind: string,
	/**  Origin reference. */
	sourceRef: string | null,
	/**  Description. */
	memo: string,
	/**  Approver, when recorded. */
	approvedBy: string | null,
	/**  The entry it reverses. */
	reversesId: number | null,
	/**  The lines. */
	lines: JournalLineDto[],
};

/**  A journal line. */
export type JournalLineDto = {
	/**  One-based. */
	lineNo: number,
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Amount in the line's currency; debit positive. */
	amount: MoneyDto,
	/**  Functional-currency amount. */
	functional: MoneyDto,
	/**  FX rate for foreign lines. */
	fxRate: string | null,
	/**  VAT code. */
	vatCode: string | null,
	/**  Free text. */
	memo: string,
};

/**  A candidate document for a bank line. */
export type MatchCandidateDto = {
	/**  E.g. `Invoice 2026-102 · Studio Brno`. */
	label: string,
	/**  Key facts. */
	detail: string,
	/**  `0.96`. */
	score: string,
	/**  `certain`, `likely`, `needs_you`, `unlikely`. */
	confidence: string,
	/**  The score as a sum of named contributions. */
	contributions: ScoreContributionDto[],
};

/**  An amount in integer minor units (`8470000` CZK is 84 700,00 Kč). */
export type MoneyDto = {
	/**  Minor units; always within ±(2^53 − 1). */
	minor: number,
	/**  ISO 4217 code. */
	currency: string,
};

/**  An accounting period. */
export type PeriodDto = {
	/**  Row id. */
	id: number,
	/**  E.g. `Q3 2026`. */
	label: string,
	/**  First day. */
	startsOn: string,
	/**  Last day. */
	endsOn: string,
	/**  `open`, `closing` or `closed`. */
	state: string,
};

/**  Profit and loss. */
export type ProfitAndLossDto = {
	/**  First day. */
	from: string,
	/**  Last day. */
	to: string,
	/**  Revenue lines. */
	revenue: StatementLineDto[],
	/**  Expense lines. */
	expenses: StatementLineDto[],
	/**  Sum of revenue. */
	totalRevenue: MoneyDto,
	/**  Sum of expenses. */
	totalExpenses: MoneyDto,
	/**  Revenue minus expenses. */
	profit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  An inbox item. */
export type ProposalDto = {
	/**  Stable id. */
	id: string,
	/**  `posting`, `deadline`, `advice`, `reminder`. */
	kind: string,
	/**  One line. */
	title: string,
	/**  Second line. */
	detail: string,
	/**  `certain`, `likely`, `needs_you`. */
	confidence: string | null,
	/**  `rule`, `matcher`, `advisor`, `calendar`. */
	sourceKind: string,
	/**  Shown as the origin, e.g. `Rule “EU SaaS”`. */
	source: string,
	/**  The bank line it came from. */
	bankLineId: string | null,
	/**  For deadlines. */
	dueOn: string | null,
	/**  The headline amount, signed as the bank line. */
	amount: MoneyDto | null,
	/**  For postings. */
	entry: ProposedEntryDto | null,
	/**  Why. */
	reasons: string[],
};

/**  A journal entry proposed by a rule, the matcher or an advisor. */
export type ProposedEntryDto = {
	/**  Accounting date. */
	date: string,
	/**  Description. */
	memo: string,
	/**  The lines. */
	lines: ProposedLineDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits (positive). */
	totalCredit: MoneyDto,
	/**  Debits equal credits; the kernel re-checks on approval. */
	balanced: boolean,
};

/**  One line of a proposed entry, split into debit and credit for display. */
export type ProposedLineDto = {
	/**  Account code. */
	account: string,
	/**  Account name (English). */
	accountName: string,
	/**  Debit, if this is a debit line. */
	debit: MoneyDto | null,
	/**  Credit, if this is a credit line. */
	credit: MoneyDto | null,
	/**  VAT code. */
	vatCode: string | null,
};

/**  One weighted reason in a match score. */
export type ScoreContributionDto = {
	/**  Why. */
	reason: string,
	/**  Signed weight as written, e.g. `+.40`. */
	weight: string,
};

/**  What a report read; see `skyla_ledger::Snapshot`. */
export type SnapshotDto = {
	/**  Posted entries read. */
	entries: number,
	/**  Highest posting sequence number read. */
	lastPostedSeq: number | null,
	/**  SHA-256 hex. */
	hash: string,
};

/**  A statement line by synthetic account. */
export type StatementLineDto = {
	/**  Account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  Amount as the statement reads. */
	amount: MoneyDto,
};

/**  Trial balance. */
export type TrialBalanceDto = {
	/**  First day, or none for everything up to `to`. */
	from: string | null,
	/**  Last day. */
	to: string,
	/**  Rows by code. */
	rows: TrialBalanceRowDto[],
	/**  Total debits. */
	totalDebit: MoneyDto,
	/**  Total credits. */
	totalCredit: MoneyDto,
	/**  What it read. */
	snapshot: SnapshotDto,
};

/**  A trial-balance row. */
export type TrialBalanceRowDto = {
	/**  Leaf account code. */
	code: string,
	/**  Czech name. */
	nameCs: string,
	/**  English name. */
	nameEn: string,
	/**  `asset`, `liability`, `equity`, `revenue`, `expense`, `closing`. */
	kind: string,
	/**  Debits. */
	debit: MoneyDto,
	/**  Credits (positive). */
	credit: MoneyDto,
	/**  Debit minus credit. */
	balance: MoneyDto,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

