//! sky-la desktop shell. Commands stay thin: each one delegates to
//! [`skyla_app::Core`], which owns every rule. tauri-specta exports their
//! signatures and types to `packages/ipc/src/bindings.ts`.

use skyla_app::dto::{
    AppInfo, BalanceSheetDto, BankStatementDto, CashBasisDto, EgressRunDto, EntityDto,
    IntegrityDto, InvoiceDto, JournalEntryDto, PeriodDto, ProfitAndLossDto, ProposalDto,
    RulePackDto, TrialBalanceDto, VatReturnDto,
};
use skyla_app::{Core, IpcFailure};
use tauri::{Runtime, State};
use tauri_specta::{Builder, collect_commands};

type Answer<T> = Result<T, IpcFailure>;

/// Build information.
#[tauri::command]
#[specta::specta]
fn app_info(core: State<'_, Core>) -> AppInfo {
    core.app_info()
}

/// The open entity.
#[tauri::command]
#[specta::specta]
fn entity(core: State<'_, Core>) -> EntityDto {
    core.entity()
}

/// Accounting periods.
#[tauri::command]
#[specta::specta]
fn periods(core: State<'_, Core>) -> Answer<Vec<PeriodDto>> {
    Ok(core.periods()?)
}

/// Profit and loss for a date range.
#[tauri::command]
#[specta::specta]
fn profit_and_loss(core: State<'_, Core>, from: String, to: String) -> Answer<ProfitAndLossDto> {
    Ok(core.profit_and_loss(&from, &to)?)
}

/// Balance sheet as of a date.
#[tauri::command]
#[specta::specta]
fn balance_sheet(core: State<'_, Core>, as_of: String) -> Answer<BalanceSheetDto> {
    Ok(core.balance_sheet(&as_of)?)
}

/// Trial balance.
#[tauri::command]
#[specta::specta]
fn trial_balance(
    core: State<'_, Core>,
    from: Option<String>,
    to: String,
) -> Answer<TrialBalanceDto> {
    Ok(core.trial_balance(from.as_deref(), &to)?)
}

/// Cash basis (*daňová evidence*) for a date range.
#[tauri::command]
#[specta::specta]
fn cash_basis(core: State<'_, Core>, from: String, to: String) -> Answer<CashBasisDto> {
    Ok(core.cash_basis(&from, &to)?)
}

/// Posted journal entries in a date range.
#[tauri::command]
#[specta::specta]
fn journal(core: State<'_, Core>, from: String, to: String) -> Answer<Vec<JournalEntryDto>> {
    Ok(core.journal(&from, &to)?)
}

/// Hash chain and balance, for the status line.
#[tauri::command]
#[specta::specta]
fn integrity(core: State<'_, Core>) -> Answer<IntegrityDto> {
    Ok(core.integrity()?)
}

/// Invoices.
#[tauri::command]
#[specta::specta]
fn invoices(core: State<'_, Core>) -> Answer<Vec<InvoiceDto>> {
    Ok(core.invoices()?)
}

/// The latest bank import with its tie-out.
#[tauri::command]
#[specta::specta]
fn bank_statement(core: State<'_, Core>) -> Answer<BankStatementDto> {
    Ok(core.bank_statement()?)
}

/// The inbox.
#[tauri::command]
#[specta::specta]
fn proposals(core: State<'_, Core>) -> Answer<Vec<ProposalDto>> {
    Ok(core.proposals()?)
}

/// The egress register.
#[tauri::command]
#[specta::specta]
fn egress_register(core: State<'_, Core>) -> Vec<EgressRunDto> {
    core.egress_register()
}

/// The DPH return for a period, mapped by the rule pack.
#[tauri::command]
#[specta::specta]
fn vat_return(core: State<'_, Core>, from: String, to: String) -> Answer<VatReturnDto> {
    Ok(core.vat_return(&from, &to)?)
}

/// The rule pack in force, with citations.
#[tauri::command]
#[specta::specta]
fn rule_pack(core: State<'_, Core>) -> RulePackDto {
    core.rule_pack()
}

/// Every command, for the invoke handler and the TypeScript export.
pub fn specta_builder<R: Runtime>() -> Builder<R> {
    Builder::<R>::new()
        .commands(collect_commands![
            app_info,
            entity,
            periods,
            profit_and_loss,
            balance_sheet,
            trial_balance,
            cash_basis,
            journal,
            integrity,
            invoices,
            bank_statement,
            proposals,
            egress_register,
            vat_return,
            rule_pack,
        ])
        // Money crosses as integer minor units; `MoneyDto` refuses anything
        // beyond 2^53 - 1, so a JavaScript number holds every value exactly.
        .dangerously_cast_bigints_to_number()
}

/// Header of the generated bindings.
pub const BINDINGS_HEADER: &str = "// Generated by tauri-specta from apps/desktop/src-tauri (`just bindings`). Don't edit.\n// biome-ignore-all lint: generated";

/// Writes the TypeScript bindings to `path`.
///
/// # Errors
/// If the export fails or the file can't be written.
pub fn export_bindings(path: &std::path::Path) -> Result<(), specta_typescript::Error> {
    specta_builder::<tauri::Wry>().export(
        specta_typescript::Typescript::default().header(BINDINGS_HEADER),
        path,
    )
}

/// Starts the desktop application on the demo entity (the unlock flow
/// arrives in WP-30).
///
/// # Panics
/// If the core or the Tauri runtime fails to start, there is nothing to recover to.
#[allow(clippy::expect_used)]
pub fn run() {
    let builder = specta_builder::<tauri::Wry>();
    let core = Core::demo().expect("the demo entity failed to open");
    tauri::Builder::default()
        .manage(core)
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running the sky-la desktop shell");
}
