//! Journal entries: drafts, validation and posting (invariants I1–I4, I7).
//!
//! Every check here is repeated by triggers in the database, so the Rust
//! errors are for clarity and the triggers are the guarantee.

use rusqlite::{Connection, OptionalExtension, params};
use serde::Serialize;
use skyla_money::{Currency, Money, Rate};

use crate::accounts::treatment_from;
use crate::{LedgerError, TaxTreatment};

/// Where an entry came from. Rule and advisor entries need approval (I7).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    /// Typed by the user.
    Manual,
    /// Generated by issuing or settling an invoice.
    Invoice,
    /// Generated by bank reconciliation.
    Bank,
    /// Proposed by a user-defined rule.
    Rule,
    /// Proposed by an advisor.
    Advisor,
    /// The reversal of another entry.
    Reversal,
    /// Opening balances.
    Opening,
}

impl SourceKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Manual => "manual",
            Self::Invoice => "invoice",
            Self::Bank => "bank",
            Self::Rule => "rule",
            Self::Advisor => "advisor",
            Self::Reversal => "reversal",
            Self::Opening => "opening",
        }
    }

    fn from_db(s: &str) -> rusqlite::Result<Self> {
        Ok(match s {
            "manual" => Self::Manual,
            "invoice" => Self::Invoice,
            "bank" => Self::Bank,
            "rule" => Self::Rule,
            "advisor" => Self::Advisor,
            "reversal" => Self::Reversal,
            "opening" => Self::Opening,
            other => {
                return Err(rusqlite::Error::InvalidColumnName(format!(
                    "source_kind {other:?}"
                )));
            }
        })
    }

    fn needs_approval(self) -> bool {
        matches!(self, Self::Rule | Self::Advisor)
    }
}

/// One line of a new entry. Debits are positive, credits negative.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewLine {
    /// Account code; must be an active leaf.
    pub account: String,
    /// Amount in the line's own currency.
    pub amount: Money,
    /// For a foreign-currency line: the functional-currency amount and the
    /// rate that produced it. `None` for functional-currency lines.
    pub conversion: Option<(Money, Rate)>,
    /// VAT classification, if the line is VAT-relevant.
    pub vat_code: Option<String>,
    /// Income-tax treatment; `None` uses the account's category default later.
    pub tax_treatment: Option<TaxTreatment>,
    /// Free text.
    pub memo: String,
}

impl NewLine {
    /// A functional-currency debit of `amount` (pass a positive amount).
    pub fn debit(account: &str, amount: Money) -> Self {
        Self {
            account: account.to_owned(),
            amount,
            conversion: None,
            vat_code: None,
            tax_treatment: None,
            memo: String::new(),
        }
    }

    /// A functional-currency credit of `amount` (pass a positive amount; it's stored negative).
    pub fn credit(account: &str, amount: Money) -> Result<Self, LedgerError> {
        Ok(Self::debit(account, amount.checked_neg()?))
    }
}

/// A new journal entry, before it exists.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewEntry {
    /// Accounting date, `YYYY-MM-DD`.
    pub date: String,
    /// Origin.
    pub source_kind: SourceKind,
    /// Identifier in the origin (invoice number, bank line id, rule id, run id).
    pub source_ref: Option<String>,
    /// Description.
    pub memo: String,
    /// Who created it: `user`, `rule:<id>` or `advisor:<run>`.
    pub created_by: String,
    /// The lines.
    pub lines: Vec<NewLine>,
}

/// Draft or posted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EntryStatus {
    /// Editable; not part of any balance.
    Draft,
    /// Final and immutable.
    Posted,
}

/// A stored line.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Line {
    /// One-based position.
    pub line_no: i64,
    /// Account code.
    pub account: String,
    /// Amount in the line's currency.
    pub amount: Money,
    /// Amount in the functional currency.
    pub functional: Money,
    /// The FX rate as stored, for foreign lines.
    pub fx_rate: Option<String>,
    /// VAT classification.
    pub vat_code: Option<String>,
    /// Income-tax treatment.
    pub tax_treatment: Option<TaxTreatment>,
    /// Free text.
    pub memo: String,
}

/// A stored entry with its lines.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Entry {
    /// Row id.
    pub id: i64,
    /// Stable unique id (UUID v7).
    pub uid: String,
    /// Accounting date.
    pub date: String,
    /// Draft or posted.
    pub status: EntryStatus,
    /// Origin.
    pub source_kind: SourceKind,
    /// Origin identifier.
    pub source_ref: Option<String>,
    /// Description.
    pub memo: String,
    /// Creator.
    pub created_by: String,
    /// Approver, when one was recorded.
    pub approved_by: Option<String>,
    /// Gapless position among posted entries.
    pub posted_seq: Option<i64>,
    /// The lines, in order.
    pub lines: Vec<Line>,
}

/// Runs `f` inside a savepoint: atomic on its own, and nests correctly inside
/// a transaction the caller already holds (e.g. a bulk import).
pub(crate) fn atomically<T>(
    conn: &Connection,
    f: impl FnOnce(&Connection) -> Result<T, LedgerError>,
) -> Result<T, LedgerError> {
    conn.execute_batch("SAVEPOINT ledger_op")?;
    match f(conn) {
        Ok(value) => {
            conn.execute_batch("RELEASE ledger_op")?;
            Ok(value)
        }
        Err(error) => {
            // Keep the original error even if the rollback itself fails.
            let _ = conn.execute_batch("ROLLBACK TO ledger_op; RELEASE ledger_op");
            Err(error)
        }
    }
}

/// True for a real calendar date written `YYYY-MM-DD`.
pub fn is_iso_date(text: &str) -> bool {
    let bytes = text.as_bytes();
    if bytes.len() != 10 || bytes[4] != b'-' || bytes[7] != b'-' {
        return false;
    }
    let number = |range: std::ops::Range<usize>| -> Option<u32> {
        let part = text.get(range)?;
        part.bytes()
            .all(|b| b.is_ascii_digit())
            .then(|| part.parse().ok())
            .flatten()
    };
    let (Some(year), Some(month), Some(day)) = (number(0..4), number(5..7), number(8..10)) else {
        return false;
    };
    let leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
    let days = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if leap => 29,
        2 => 28,
        _ => return false,
    };
    (1..=days).contains(&day)
}

/// Sets the ledger's functional currency. Changing it is refused once anything is booked.
pub fn set_functional_currency(conn: &Connection, currency: Currency) -> Result<(), LedgerError> {
    conn.execute(
        "INSERT INTO ledger_setting (key, value) VALUES ('functional_currency', ?1)
         ON CONFLICT (key) DO UPDATE SET value = excluded.value",
        [currency.code()],
    )?;
    Ok(())
}

/// The ledger's functional currency.
pub fn functional_currency(conn: &Connection) -> Result<Currency, LedgerError> {
    let code: Option<String> = conn
        .query_row(
            "SELECT value FROM ledger_setting WHERE key = 'functional_currency'",
            [],
            |r| r.get(0),
        )
        .optional()?;
    let code = code.ok_or(LedgerError::FunctionalCurrencyNotSet)?;
    Ok(Currency::from_code(&code)?)
}

/// Looks up a postable account, explaining why it isn't postable when it isn't.
fn postable_account(conn: &Connection, code: &str) -> Result<i64, LedgerError> {
    let row: Option<(i64, bool, bool)> = conn
        .query_row(
            "SELECT id, is_leaf, active FROM account_with_leaf WHERE code = ?1",
            [code],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
        )
        .optional()?;
    match row {
        None => Err(LedgerError::UnknownAccount(code.to_owned())),
        Some((_, false, _)) => Err(LedgerError::AccountNotPostable {
            code: code.to_owned(),
            reason: "it has sub-accounts",
        }),
        Some((_, _, false)) => Err(LedgerError::AccountNotPostable {
            code: code.to_owned(),
            reason: "it is inactive",
        }),
        Some((id, true, true)) => Ok(id),
    }
}

fn validate_line(index: usize, line: &NewLine, functional: Currency) -> Result<Money, LedgerError> {
    let bad = |reason: &str| LedgerError::InvalidLine {
        line: index + 1,
        reason: reason.to_owned(),
    };
    if line.amount.is_zero() {
        return Err(bad("amount is zero"));
    }
    let functional_amount = match (&line.conversion, line.amount.currency() == functional) {
        (None, true) => line.amount,
        (Some(_), true) => return Err(bad("a functional-currency line has no conversion")),
        (None, false) => {
            return Err(bad(
                "a foreign-currency line needs its functional amount and FX rate",
            ));
        }
        (Some((converted, rate)), false) => {
            if converted.currency() != functional {
                return Err(bad(
                    "the converted amount must be in the functional currency",
                ));
            }
            if rate.is_sign_negative() || rate.is_zero() {
                return Err(bad("the FX rate must be positive"));
            }
            if converted.is_zero() || converted.is_negative() != line.amount.is_negative() {
                return Err(bad(
                    "the converted amount must be non-zero with the same sign",
                ));
            }
            *converted
        }
    };
    Ok(functional_amount)
}

/// Stores a new draft entry and returns its id. Drafts may be unbalanced while
/// they're being edited; posting enforces balance.
pub fn create_draft(conn: &Connection, entry: &NewEntry) -> Result<i64, LedgerError> {
    if !is_iso_date(&entry.date) {
        return Err(LedgerError::InvalidDate(entry.date.clone()));
    }
    let functional = functional_currency(conn)?;
    atomically(conn, |tx| {
        tx.execute(
        "INSERT INTO journal_entry (uid, entry_date, source_kind, source_ref, memo, created_by) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![uuid::Uuid::now_v7().to_string(), entry.date, entry.source_kind.as_str(), entry.source_ref, entry.memo, entry.created_by],
    )?;
        let id = tx.last_insert_rowid();
        for (index, line) in entry.lines.iter().enumerate() {
            let functional_amount = validate_line(index, line, functional)?;
            let account_id = postable_account(tx, &line.account)?;
            tx.execute(
            "INSERT INTO posting (entry_id, line_no, account_id, amount_minor, currency, amount_func_minor, fx_rate, vat_code, tax_treatment, memo)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
            params![
                id,
                i64::try_from(index + 1).unwrap_or(i64::MAX),
                account_id,
                line.amount.minor(),
                line.amount.currency().code(),
                functional_amount.minor(),
                line.conversion.as_ref().map(|(_, rate)| rate.to_string()),
                line.vat_code,
                line.tax_treatment.map(|t| t.as_str()),
                line.memo,
            ],
        )?;
        }
        Ok(id)
    })
}

/// Deletes a draft. Posted entries can't be deleted.
pub fn delete_draft(conn: &Connection, id: i64) -> Result<(), LedgerError> {
    let entry = get_entry(conn, id)?;
    if entry.status == EntryStatus::Posted {
        return Err(LedgerError::AlreadyPosted(id));
    }
    conn.execute("DELETE FROM journal_entry WHERE id = ?1", [id])?;
    Ok(())
}

/// Posts a draft, making it final. Returns its gapless posting sequence number.
///
/// Checks, in order: still a draft, at least two lines, balanced in the
/// functional currency (I1), an open period covers the date (I3), approval
/// for rule- and advisor-sourced entries (I7). Accounts were checked when the
/// lines were written (I4); the database re-checks all of it.
pub fn post_entry(
    conn: &Connection,
    id: i64,
    approved_by: Option<&str>,
) -> Result<i64, LedgerError> {
    let entry = get_entry(conn, id)?;
    if entry.status == EntryStatus::Posted {
        return Err(LedgerError::AlreadyPosted(id));
    }
    if entry.lines.len() < 2 {
        return Err(LedgerError::TooFewLines);
    }
    let functional = functional_currency(conn)?;
    let difference = Money::sum(functional, entry.lines.iter().map(|l| l.functional))?;
    if !difference.is_zero() {
        return Err(LedgerError::Unbalanced { difference });
    }
    let period: Option<(i64, String)> = conn
        .query_row(
            "SELECT id, state FROM period WHERE ?1 BETWEEN starts_on AND ends_on",
            [&entry.date],
            |r| Ok((r.get(0)?, r.get(1)?)),
        )
        .optional()?;
    let period_id = match period {
        None => return Err(LedgerError::NoPeriod(entry.date)),
        Some((_, state)) if state == "closed" => return Err(LedgerError::PeriodClosed(entry.date)),
        Some((pid, _)) => pid,
    };
    let approver = approved_by.filter(|a| !a.trim().is_empty());
    if entry.source_kind.needs_approval() && approver.is_none() {
        return Err(LedgerError::NeedsApproval);
    }

    // I4 again: an account may have been deactivated since the draft was written.
    for line in &entry.lines {
        postable_account(conn, &line.account)?;
    }

    atomically(conn, |tx| {
        let seq: i64 = tx.query_row(
            "SELECT coalesce(max(posted_seq), 0) + 1 FROM journal_entry",
            [],
            |r| r.get(0),
        )?;
        tx.execute(
            "UPDATE journal_entry
         SET status = 'posted', period_id = ?2, posted_seq = ?3, approved_by = ?4,
             posted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
         WHERE id = ?1",
            params![id, period_id, seq, approver],
        )?;
        Ok(seq)
    })
}

/// Loads an entry and its lines.
pub fn get_entry(conn: &Connection, id: i64) -> Result<Entry, LedgerError> {
    let header = conn
        .query_row(
            "SELECT id, uid, entry_date, status, source_kind, source_ref, memo, created_by, approved_by, posted_seq
             FROM journal_entry WHERE id = ?1",
            [id],
            |r| {
                Ok((
                    r.get::<_, i64>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, String>(2)?,
                    r.get::<_, String>(3)?,
                    r.get::<_, String>(4)?,
                    r.get::<_, Option<String>>(5)?,
                    r.get::<_, String>(6)?,
                    r.get::<_, String>(7)?,
                    r.get::<_, Option<String>>(8)?,
                    r.get::<_, Option<i64>>(9)?,
                ))
            },
        )
        .optional()?
        .ok_or(LedgerError::EntryNotFound(id))?;
    let functional = functional_currency(conn)?;

    let mut stmt = conn.prepare(
        "SELECT p.line_no, a.code, p.amount_minor, p.currency, p.amount_func_minor, p.fx_rate, p.vat_code, p.tax_treatment, p.memo
         FROM posting p JOIN account a ON a.id = p.account_id WHERE p.entry_id = ?1 ORDER BY p.line_no",
    )?;
    let lines = stmt
        .query_map([id], |r| {
            let currency: String = r.get(3)?;
            let currency = Currency::from_code(&currency).map_err(|e| {
                rusqlite::Error::FromSqlConversionFailure(
                    3,
                    rusqlite::types::Type::Text,
                    Box::new(e),
                )
            })?;
            let treatment: Option<String> = r.get(7)?;
            Ok(Line {
                line_no: r.get(0)?,
                account: r.get(1)?,
                amount: Money::new(r.get(2)?, currency),
                functional: Money::new(r.get(4)?, functional),
                fx_rate: r.get(5)?,
                vat_code: r.get(6)?,
                tax_treatment: treatment
                    .as_deref()
                    .map(|t| treatment_from(7, t))
                    .transpose()?,
                memo: r.get(8)?,
            })
        })?
        .collect::<Result<Vec<_>, _>>()?;
    let (id, uid, date, status, source_kind, source_ref, memo, created_by, approved_by, posted_seq) =
        header;
    Ok(Entry {
        id,
        uid,
        date,
        status: if status == "posted" {
            EntryStatus::Posted
        } else {
            EntryStatus::Draft
        },
        source_kind: SourceKind::from_db(&source_kind)?,
        source_ref,
        memo,
        created_by,
        approved_by,
        posted_seq,
        lines,
    })
}
