//! Journal entries: drafts, validation, posting (invariants I1–I4, I7) and reversals.
//!
//! Every check here is repeated by triggers in the database, so the Rust
//! errors are for clarity and the triggers are the guarantee.

use rusqlite::{Connection, OptionalExtension, params};
use serde::Serialize;
use skyla_money::{Currency, Money, Rate};

use crate::accounts::treatment_from;
use crate::chain::hash_for_post;
use crate::{LedgerError, TaxTreatment};

/// Where an entry came from. Rule and advisor entries need approval (I7).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    /// Typed by the user.
    Manual,
    /// Generated by issuing or settling an invoice.
    Invoice,
    /// Generated by bank reconciliation.
    Bank,
    /// Proposed by a user-defined rule.
    Rule,
    /// Proposed by an advisor.
    Advisor,
    /// The reversal of another entry.
    Reversal,
    /// Opening balances.
    Opening,
}

impl SourceKind {
    /// The stored name, e.g. `invoice`.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Manual => "manual",
            Self::Invoice => "invoice",
            Self::Bank => "bank",
            Self::Rule => "rule",
            Self::Advisor => "advisor",
            Self::Reversal => "reversal",
            Self::Opening => "opening",
        }
    }

    fn from_db(s: &str) -> rusqlite::Result<Self> {
        Ok(match s {
            "manual" => Self::Manual,
            "invoice" => Self::Invoice,
            "bank" => Self::Bank,
            "rule" => Self::Rule,
            "advisor" => Self::Advisor,
            "reversal" => Self::Reversal,
            "opening" => Self::Opening,
            other => {
                return Err(rusqlite::Error::InvalidColumnName(format!(
                    "source_kind {other:?}"
                )));
            }
        })
    }

    fn needs_approval(self) -> bool {
        matches!(self, Self::Rule | Self::Advisor)
    }
}

/// One line of a new entry. Debits are positive, credits negative.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewLine {
    /// Account code; must be an active leaf.
    pub account: String,
    /// Amount in the line's own currency.
    pub amount: Money,
    /// For a foreign-currency line: the functional-currency amount and the
    /// rate that produced it. `None` for functional-currency lines.
    pub conversion: Option<(Money, Rate)>,
    /// VAT classification, if the line is VAT-relevant.
    pub vat_code: Option<String>,
    /// Income-tax treatment; `None` uses the account's category default later.
    pub tax_treatment: Option<TaxTreatment>,
    /// Free text.
    pub memo: String,
}

impl NewLine {
    /// A functional-currency debit of `amount` (pass a positive amount).
    pub fn debit(account: &str, amount: Money) -> Self {
        Self {
            account: account.to_owned(),
            amount,
            conversion: None,
            vat_code: None,
            tax_treatment: None,
            memo: String::new(),
        }
    }

    /// A functional-currency credit of `amount` (pass a positive amount; it's stored negative).
    pub fn credit(account: &str, amount: Money) -> Result<Self, LedgerError> {
        Ok(Self::debit(account, amount.checked_neg()?))
    }
}

/// A new journal entry, before it exists.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewEntry {
    /// Accounting date, `YYYY-MM-DD`.
    pub date: String,
    /// Origin.
    pub source_kind: SourceKind,
    /// Identifier in the origin (invoice number, bank line id, rule id, run id).
    pub source_ref: Option<String>,
    /// Description.
    pub memo: String,
    /// Who created it: `user`, `rule:<id>` or `advisor:<run>`.
    pub created_by: String,
    /// The lines.
    pub lines: Vec<NewLine>,
}

/// Draft or posted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EntryStatus {
    /// Editable; not part of any balance.
    Draft,
    /// Final and immutable.
    Posted,
}

/// A stored line.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Line {
    /// One-based position.
    pub line_no: i64,
    /// Account code.
    pub account: String,
    /// Amount in the line's currency.
    pub amount: Money,
    /// Amount in the functional currency.
    pub functional: Money,
    /// The FX rate as stored, for foreign lines.
    pub fx_rate: Option<String>,
    /// VAT classification.
    pub vat_code: Option<String>,
    /// Income-tax treatment.
    pub tax_treatment: Option<TaxTreatment>,
    /// Free text.
    pub memo: String,
}

/// A stored entry with its lines.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Entry {
    /// Row id.
    pub id: i64,
    /// Stable unique id (UUID v7).
    pub uid: String,
    /// Accounting date.
    pub date: String,
    /// Draft or posted.
    pub status: EntryStatus,
    /// Origin.
    pub source_kind: SourceKind,
    /// Origin identifier.
    pub source_ref: Option<String>,
    /// Description.
    pub memo: String,
    /// Creator.
    pub created_by: String,
    /// Approver, when one was recorded.
    pub approved_by: Option<String>,
    /// Gapless position among posted entries.
    pub posted_seq: Option<i64>,
    /// When it was posted (UTC, RFC 3339).
    pub posted_at: Option<String>,
    /// For a reversal: the entry it reverses.
    pub reverses_id: Option<i64>,
    /// Its link in the journal hash chain (hex), once posted.
    pub chain_hash: Option<String>,
    /// The lines, in order.
    pub lines: Vec<Line>,
}

/// Runs `f` inside a savepoint: atomic on its own, and nests correctly inside
/// a transaction the caller already holds (e.g. a bulk import).
pub(crate) fn atomically<T>(
    conn: &Connection,
    f: impl FnOnce(&Connection) -> Result<T, LedgerError>,
) -> Result<T, LedgerError> {
    conn.execute_batch("SAVEPOINT ledger_op")?;
    match f(conn) {
        Ok(value) => {
            conn.execute_batch("RELEASE ledger_op")?;
            Ok(value)
        }
        Err(error) => {
            // Keep the original error even if the rollback itself fails.
            let _ = conn.execute_batch("ROLLBACK TO ledger_op; RELEASE ledger_op");
            Err(error)
        }
    }
}

/// True for a real calendar date written `YYYY-MM-DD`.
pub fn is_iso_date(text: &str) -> bool {
    let bytes = text.as_bytes();
    if bytes.len() != 10 || bytes[4] != b'-' || bytes[7] != b'-' {
        return false;
    }
    let number = |range: std::ops::Range<usize>| -> Option<u32> {
        let part = text.get(range)?;
        part.bytes()
            .all(|b| b.is_ascii_digit())
            .then(|| part.parse().ok())
            .flatten()
    };
    let (Some(year), Some(month), Some(day)) = (number(0..4), number(5..7), number(8..10)) else {
        return false;
    };
    let leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
    let days = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if leap => 29,
        2 => 28,
        _ => return false,
    };
    (1..=days).contains(&day)
}

/// Sets the ledger's functional currency. Changing it is refused once anything is booked.
pub fn set_functional_currency(conn: &Connection, currency: Currency) -> Result<(), LedgerError> {
    conn.execute(
        "INSERT INTO ledger_setting (key, value) VALUES ('functional_currency', ?1)
         ON CONFLICT (key) DO UPDATE SET value = excluded.value",
        [currency.code()],
    )?;
    Ok(())
}

/// The ledger's functional currency.
pub fn functional_currency(conn: &Connection) -> Result<Currency, LedgerError> {
    let code: Option<String> = conn
        .query_row(
            "SELECT value FROM ledger_setting WHERE key = 'functional_currency'",
            [],
            |r| r.get(0),
        )
        .optional()?;
    let code = code.ok_or(LedgerError::FunctionalCurrencyNotSet)?;
    Ok(Currency::from_code(&code)?)
}

/// Looks up a postable account, explaining why it isn't postable when it isn't.
fn postable_account(conn: &Connection, code: &str) -> Result<i64, LedgerError> {
    let row: Option<(i64, bool, bool)> = conn
        .query_row(
            "SELECT id, is_leaf, active FROM account_with_leaf WHERE code = ?1",
            [code],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
        )
        .optional()?;
    match row {
        None => Err(LedgerError::UnknownAccount(code.to_owned())),
        Some((_, false, _)) => Err(LedgerError::AccountNotPostable {
            code: code.to_owned(),
            reason: "it has sub-accounts",
        }),
        Some((_, _, false)) => Err(LedgerError::AccountNotPostable {
            code: code.to_owned(),
            reason: "it is inactive",
        }),
        Some((id, true, true)) => Ok(id),
    }
}

fn validate_line(index: usize, line: &NewLine, functional: Currency) -> Result<Money, LedgerError> {
    let bad = |reason: &str| LedgerError::InvalidLine {
        line: index + 1,
        reason: reason.to_owned(),
    };
    if line.amount.is_zero() {
        return Err(bad("amount is zero"));
    }
    let functional_amount = match (&line.conversion, line.amount.currency() == functional) {
        (None, true) => line.amount,
        (Some(_), true) => return Err(bad("a functional-currency line has no conversion")),
        (None, false) => {
            return Err(bad(
                "a foreign-currency line needs its functional amount and FX rate",
            ));
        }
        (Some((converted, rate)), false) => {
            if converted.currency() != functional {
                return Err(bad(
                    "the converted amount must be in the functional currency",
                ));
            }
            if rate.is_sign_negative() || rate.is_zero() {
                return Err(bad("the FX rate must be positive"));
            }
            if converted.is_zero() || converted.is_negative() != line.amount.is_negative() {
                return Err(bad(
                    "the converted amount must be non-zero with the same sign",
                ));
            }
            *converted
        }
    };
    Ok(functional_amount)
}

/// Stores a new draft entry and returns its id. Drafts may be unbalanced while
/// they're being edited; posting enforces balance.
pub fn create_draft(conn: &Connection, entry: &NewEntry) -> Result<i64, LedgerError> {
    if entry.source_kind == SourceKind::Reversal {
        return Err(LedgerError::InvalidEntry(
            "reversals are created with reverse_entry".into(),
        ));
    }
    insert_draft(conn, entry, None, None)
}

/// Checks that `entry` would post, with every rule [`post_entry`] and the
/// database apply, and leaves nothing behind: the draft and the posting are
/// always rolled back. For proposals (an advisor's or a rule's), which a
/// person approves before anything is stored.
pub fn check_entry(conn: &Connection, entry: &NewEntry) -> Result<(), LedgerError> {
    conn.execute_batch("SAVEPOINT ledger_check")?;
    let result =
        create_draft(conn, entry).and_then(|id| post_entry(conn, id, Some("check")).map(|_| ()));
    // Whatever happened, undo it; keep the check's own error if the undo fails too.
    let undone = conn.execute_batch("ROLLBACK TO ledger_check; RELEASE ledger_check");
    result?;
    undone?;
    Ok(())
}

/// [`create_draft`] with a given uid instead of a fresh UUID v7. For
/// replaying or importing books whose entry identities are known, and for
/// reproducible demos: the uid is part of the hash chain.
pub fn create_draft_as(conn: &Connection, entry: &NewEntry, uid: &str) -> Result<i64, LedgerError> {
    if entry.source_kind == SourceKind::Reversal {
        return Err(LedgerError::InvalidEntry(
            "reversals are created with reverse_entry".into(),
        ));
    }
    insert_draft(conn, entry, None, Some(canonical_uid(uid)?))
}

/// A uid must be a UUID in its canonical lowercase, hyphenated form.
fn canonical_uid(uid: &str) -> Result<&str, LedgerError> {
    match uuid::Uuid::parse_str(uid) {
        Ok(parsed) if parsed.hyphenated().to_string() == uid => Ok(uid),
        _ => Err(LedgerError::InvalidEntry(format!(
            "entry uid {uid:?} isn't a canonical UUID"
        ))),
    }
}

/// A known identity for a replayed posting: its uid and posting time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Replay<'a> {
    /// Canonical UUID.
    pub uid: &'a str,
    /// `YYYY-MM-DDTHH:MM:SS.sssZ`.
    pub posted_at: &'a str,
}

fn insert_draft(
    conn: &Connection,
    entry: &NewEntry,
    reverses_id: Option<i64>,
    uid: Option<&str>,
) -> Result<i64, LedgerError> {
    if !is_iso_date(&entry.date) {
        return Err(LedgerError::InvalidDate(entry.date.clone()));
    }
    let functional = functional_currency(conn)?;
    atomically(conn, |tx| {
        tx.execute(
        "INSERT INTO journal_entry (uid, entry_date, source_kind, source_ref, memo, created_by, reverses_id) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
        params![uid.map_or_else(|| uuid::Uuid::now_v7().to_string(), str::to_owned), entry.date, entry.source_kind.as_str(), entry.source_ref, entry.memo, entry.created_by, reverses_id],
    )?;
        let id = tx.last_insert_rowid();
        for (index, line) in entry.lines.iter().enumerate() {
            let functional_amount = validate_line(index, line, functional)?;
            let account_id = postable_account(tx, &line.account)?;
            tx.execute(
            "INSERT INTO posting (entry_id, line_no, account_id, amount_minor, currency, amount_func_minor, fx_rate, vat_code, tax_treatment, memo)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
            params![
                id,
                i64::try_from(index + 1).unwrap_or(i64::MAX),
                account_id,
                line.amount.minor(),
                line.amount.currency().code(),
                functional_amount.minor(),
                line.conversion.as_ref().map(|(_, rate)| rate.to_string()),
                line.vat_code,
                line.tax_treatment.map(|t| t.as_str()),
                line.memo,
            ],
        )?;
        }
        Ok(id)
    })
}

/// Deletes a draft. Posted entries can't be deleted.
pub fn delete_draft(conn: &Connection, id: i64) -> Result<(), LedgerError> {
    let entry = get_entry(conn, id)?;
    if entry.status == EntryStatus::Posted {
        return Err(LedgerError::AlreadyPosted(id));
    }
    atomically(conn, |tx| {
        tx.execute("DELETE FROM settlement WHERE cash_entry_id = ?1", [id])?;
        tx.execute("DELETE FROM posting WHERE entry_id = ?1", [id])?;
        tx.execute("DELETE FROM journal_entry WHERE id = ?1", [id])?;
        Ok(())
    })
}

/// Posts a draft, making it final. Returns its gapless posting sequence number.
///
/// Checks, in order: still a draft, at least two lines, balanced in the
/// functional currency (I1), an open period covers the date (I3), approval
/// for rule- and advisor-sourced entries (I7), active leaf accounts (I4, again).
/// The same transaction links the entry into the hash chain (D-007). The
/// database re-checks all of it.
pub fn post_entry(
    conn: &Connection,
    id: i64,
    approved_by: Option<&str>,
) -> Result<i64, LedgerError> {
    post_entry_at(conn, id, approved_by, None)
}

/// True for a UTC timestamp written `YYYY-MM-DDTHH:MM:SS.sssZ`.
fn is_posting_time(text: &str) -> bool {
    let b = text.as_bytes();
    b.len() == 24
        && is_iso_date(&text[..10])
        && b[10] == b'T'
        && b[13] == b':'
        && b[16] == b':'
        && b[19] == b'.'
        && b[23] == b'Z'
        && [11, 12, 14, 15, 17, 18, 20, 21, 22]
            .iter()
            .all(|&i| b[i].is_ascii_digit())
        && text[11..13] < *"24"
        && text[14..16] < *"60"
        && text[17..19] < *"60"
}

/// [`post_entry`] with a given posting time (`YYYY-MM-DDTHH:MM:SS.sssZ`, UTC)
/// instead of now. For replaying or importing books whose posting times are
/// known, and for reproducible demos: the time is part of the hash chain.
pub fn post_entry_at(
    conn: &Connection,
    id: i64,
    approved_by: Option<&str>,
    posted_at: Option<&str>,
) -> Result<i64, LedgerError> {
    if let Some(time) = posted_at
        && !is_posting_time(time)
    {
        return Err(LedgerError::InvalidEntry(format!(
            "posting time {time:?} isn't YYYY-MM-DDTHH:MM:SS.sssZ"
        )));
    }
    let entry = get_entry(conn, id)?;
    if entry.status == EntryStatus::Posted {
        return Err(LedgerError::AlreadyPosted(id));
    }
    if entry.lines.len() < 2 {
        return Err(LedgerError::TooFewLines);
    }
    let functional = functional_currency(conn)?;
    let difference = Money::sum(functional, entry.lines.iter().map(|l| l.functional))?;
    if !difference.is_zero() {
        return Err(LedgerError::Unbalanced { difference });
    }
    let period: Option<(i64, String)> = conn
        .query_row(
            "SELECT id, state FROM period WHERE ?1 BETWEEN starts_on AND ends_on",
            [&entry.date],
            |r| Ok((r.get(0)?, r.get(1)?)),
        )
        .optional()?;
    let period_id = match period {
        None => return Err(LedgerError::NoPeriod(entry.date)),
        Some((_, state)) if state == "closed" => return Err(LedgerError::PeriodClosed(entry.date)),
        Some((pid, _)) => pid,
    };
    let approver = approved_by.filter(|a| !a.trim().is_empty());
    if entry.source_kind.needs_approval() && approver.is_none() {
        return Err(LedgerError::NeedsApproval);
    }

    // I4 again: an account may have been deactivated since the draft was written.
    for line in &entry.lines {
        postable_account(conn, &line.account)?;
    }

    atomically(conn, |tx| {
        let seq: i64 = tx.query_row(
            "SELECT coalesce(max(posted_seq), 0) + 1 FROM journal_entry",
            [],
            |r| r.get(0),
        )?;
        let posted_at: String = match posted_at {
            Some(time) => time.to_owned(),
            None => tx.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", [], |r| {
                r.get(0)
            })?,
        };
        let chain_hash = hash_for_post(tx, id, seq, &posted_at, approver)?;
        tx.execute(
            "UPDATE journal_entry
             SET status = 'posted', period_id = ?2, posted_seq = ?3, approved_by = ?4,
                 posted_at = ?5, chain_hash = ?6
             WHERE id = ?1",
            params![id, period_id, seq, approver, posted_at, chain_hash],
        )?;
        Ok(seq)
    })
}

/// Records that the draft `cash_entry_id` (a payment, receipt or offset)
/// settles `amount` of the posted entry `settled_entry_id` (an invoice, say).
/// The cash basis recognises the settled entry's income and expense, pro
/// rata, on the payment's date. Links freeze when the payment posts; together
/// they can't exceed the settled entry's gross (its debit total).
pub fn link_settlement(
    conn: &Connection,
    cash_entry_id: i64,
    settled_entry_id: i64,
    amount: Money,
) -> Result<(), LedgerError> {
    let cash = get_entry(conn, cash_entry_id)?;
    if cash.status == EntryStatus::Posted {
        return Err(LedgerError::AlreadyPosted(cash_entry_id));
    }
    let settled = get_entry(conn, settled_entry_id)?;
    if settled.status != EntryStatus::Posted {
        return Err(LedgerError::NotPosted(settled_entry_id));
    }
    if amount.currency() != functional_currency(conn)? || amount.is_zero() || amount.is_negative() {
        return Err(LedgerError::InvalidEntry(
            "a settlement is a positive amount in the functional currency".into(),
        ));
    }
    conn.execute(
        "INSERT INTO settlement (cash_entry_id, settled_entry_id, amount_func_minor) VALUES (?1, ?2, ?3)",
        params![cash_entry_id, settled_entry_id, amount.minor()],
    )?;
    Ok(())
}

/// A posted reversal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Reversal {
    /// The new entry.
    pub entry_id: i64,
    /// Its posting sequence number.
    pub posted_seq: i64,
}

/// Reverses a posted entry: posts a new entry dated `date` whose lines mirror
/// the original's with the opposite sign, linked through `reverses_id`. This
/// is the only way to correct a posted entry (I2). The date must fall in an
/// open period and not before the original; an entry is reversed at most once.
pub fn reverse_entry(
    conn: &Connection,
    id: i64,
    date: &str,
    created_by: &str,
    memo: Option<&str>,
) -> Result<Reversal, LedgerError> {
    reverse_entry_at(conn, id, date, created_by, memo, None)
}

/// [`reverse_entry`] with a known uid and posting time for the reversal; see
/// [`create_draft_as`] and [`post_entry_at`].
pub fn reverse_entry_at(
    conn: &Connection,
    id: i64,
    date: &str,
    created_by: &str,
    memo: Option<&str>,
    replay: Option<Replay<'_>>,
) -> Result<Reversal, LedgerError> {
    let uid = replay.map(|r| canonical_uid(r.uid)).transpose()?;
    let original = get_entry(conn, id)?;
    let Some(seq) = original.posted_seq else {
        return Err(LedgerError::NotPosted(id));
    };
    if !is_iso_date(date) {
        return Err(LedgerError::InvalidDate(date.to_owned()));
    }
    if date < original.date.as_str() {
        return Err(LedgerError::InvalidEntry(format!(
            "a reversal can't be dated {date}, before the entry it reverses ({})",
            original.date
        )));
    }
    let already: Option<i64> = conn
        .query_row(
            "SELECT id FROM journal_entry WHERE reverses_id = ?1",
            [id],
            |r| r.get(0),
        )
        .optional()?;
    if already.is_some() {
        return Err(LedgerError::AlreadyReversed(id));
    }
    let lines = original
        .lines
        .iter()
        .map(|line| {
            let conversion = match &line.fx_rate {
                None => None,
                Some(rate) => Some((
                    line.functional.checked_neg()?,
                    rate.parse::<Rate>().map_err(|_| LedgerError::InvalidLine {
                        line: usize::try_from(line.line_no).unwrap_or(0),
                        reason: format!("stored FX rate {rate:?} is unreadable"),
                    })?,
                )),
            };
            Ok(NewLine {
                account: line.account.clone(),
                amount: line.amount.checked_neg()?,
                conversion,
                vat_code: line.vat_code.clone(),
                tax_treatment: line.tax_treatment,
                memo: line.memo.clone(),
            })
        })
        .collect::<Result<Vec<_>, LedgerError>>()?;
    let reversal = NewEntry {
        date: date.to_owned(),
        source_kind: SourceKind::Reversal,
        source_ref: Some(original.uid.clone()),
        memo: memo.map_or_else(
            || format!("Reversal of entry {seq}: {}", original.memo),
            str::to_owned,
        ),
        created_by: created_by.to_owned(),
        lines,
    };
    atomically(conn, |tx| {
        let entry_id = insert_draft(tx, &reversal, Some(id), uid)?;
        // A reversed payment un-settles what it settled.
        tx.execute(
            "INSERT INTO settlement (cash_entry_id, settled_entry_id, amount_func_minor)
             SELECT ?1, settled_entry_id, -amount_func_minor FROM settlement WHERE cash_entry_id = ?2",
            params![entry_id, id],
        )?;
        let posted_seq = post_entry_at(tx, entry_id, None, replay.map(|r| r.posted_at))?;
        Ok(Reversal {
            entry_id,
            posted_seq,
        })
    })
}

/// Loads an entry and its lines.
pub fn get_entry(conn: &Connection, id: i64) -> Result<Entry, LedgerError> {
    let header = conn
        .query_row(
            "SELECT id, uid, entry_date, status, source_kind, source_ref, memo, created_by, approved_by, posted_seq,
                    posted_at, reverses_id, chain_hash
             FROM journal_entry WHERE id = ?1",
            [id],
            |r| {
                Ok((
                    r.get::<_, i64>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, String>(2)?,
                    r.get::<_, String>(3)?,
                    r.get::<_, String>(4)?,
                    r.get::<_, Option<String>>(5)?,
                    r.get::<_, String>(6)?,
                    r.get::<_, String>(7)?,
                    r.get::<_, Option<String>>(8)?,
                    r.get::<_, Option<i64>>(9)?,
                    (
                        r.get::<_, Option<String>>(10)?,
                        r.get::<_, Option<i64>>(11)?,
                        r.get::<_, Option<String>>(12)?,
                    ),
                ))
            },
        )
        .optional()?
        .ok_or(LedgerError::EntryNotFound(id))?;
    let functional = functional_currency(conn)?;

    let mut stmt = conn.prepare(
        "SELECT p.line_no, a.code, p.amount_minor, p.currency, p.amount_func_minor, p.fx_rate, p.vat_code, p.tax_treatment, p.memo
         FROM posting p JOIN account a ON a.id = p.account_id WHERE p.entry_id = ?1 ORDER BY p.line_no",
    )?;
    let lines = stmt
        .query_map([id], |r| {
            let currency: String = r.get(3)?;
            let currency = Currency::from_code(&currency).map_err(|e| {
                rusqlite::Error::FromSqlConversionFailure(
                    3,
                    rusqlite::types::Type::Text,
                    Box::new(e),
                )
            })?;
            let treatment: Option<String> = r.get(7)?;
            Ok(Line {
                line_no: r.get(0)?,
                account: r.get(1)?,
                amount: Money::new(r.get(2)?, currency),
                functional: Money::new(r.get(4)?, functional),
                fx_rate: r.get(5)?,
                vat_code: r.get(6)?,
                tax_treatment: treatment
                    .as_deref()
                    .map(|t| treatment_from(7, t))
                    .transpose()?,
                memo: r.get(8)?,
            })
        })?
        .collect::<Result<Vec<_>, _>>()?;
    let (
        id,
        uid,
        date,
        status,
        source_kind,
        source_ref,
        memo,
        created_by,
        approved_by,
        posted_seq,
        (posted_at, reverses_id, chain_hash),
    ) = header;
    Ok(Entry {
        id,
        uid,
        date,
        status: if status == "posted" {
            EntryStatus::Posted
        } else {
            EntryStatus::Draft
        },
        source_kind: SourceKind::from_db(&source_kind)?,
        source_ref,
        memo,
        created_by,
        approved_by,
        posted_seq,
        posted_at,
        reverses_id,
        chain_hash,
        lines,
    })
}

/// Posted entries dated `from..=to`, in posting order.
pub fn list_posted(conn: &Connection, from: &str, to: &str) -> Result<Vec<Entry>, LedgerError> {
    for date in [from, to] {
        if !is_iso_date(date) {
            return Err(LedgerError::InvalidDate(date.to_owned()));
        }
    }
    let ids: Vec<i64> = conn
        .prepare_cached(
            "SELECT id FROM journal_entry
             WHERE status = 'posted' AND entry_date BETWEEN ?1 AND ?2 ORDER BY posted_seq",
        )?
        .query_map([from, to], |r| r.get(0))?
        .collect::<Result<_, _>>()?;
    ids.into_iter().map(|id| get_entry(conn, id)).collect()
}

/// The posted entry whose origin reference is `source_ref` (an invoice
/// number, say), if there is exactly one.
pub fn find_posted_by_ref(
    conn: &Connection,
    source_kind: SourceKind,
    source_ref: &str,
) -> Result<Option<i64>, LedgerError> {
    let ids: Vec<i64> = conn
        .prepare_cached(
            "SELECT id FROM journal_entry
             WHERE status = 'posted' AND source_kind = ?1 AND source_ref = ?2 LIMIT 2",
        )?
        .query_map([source_kind.as_str(), source_ref], |r| r.get(0))?
        .collect::<Result<_, _>>()?;
    Ok(match ids.as_slice() {
        [id] => Some(*id),
        _ => None,
    })
}

/// One posted payment against a settled entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SettlementLink {
    /// The paying entry.
    pub cash_entry_id: i64,
    /// Its date.
    pub date: String,
    /// The amount it settled (negative for a reversed payment).
    pub amount: Money,
}

/// The posted payments that settle `settled_entry_id`, by date.
pub fn settlements_of(
    conn: &Connection,
    settled_entry_id: i64,
) -> Result<Vec<SettlementLink>, LedgerError> {
    let currency = functional_currency(conn)?;
    let links = conn
        .prepare_cached(
            "SELECT s.cash_entry_id, c.entry_date, s.amount_func_minor
             FROM settlement s JOIN journal_entry c ON c.id = s.cash_entry_id
             WHERE s.settled_entry_id = ?1 AND c.status = 'posted'
             ORDER BY c.entry_date, c.posted_seq",
        )?
        .query_map([settled_entry_id], |r| {
            Ok(SettlementLink {
                cash_entry_id: r.get(0)?,
                date: r.get(1)?,
                amount: Money::new(r.get(2)?, currency),
            })
        })?
        .collect::<Result<_, _>>()?;
    Ok(links)
}
